import type { KamusBahasa } from './id'

/**
 * قاموس اللغة العربية (ar) — Arabic Dictionary Placeholder (G2 Prep / RTL Layout)
 */
export const ar: KamusBahasa = {
  umum: {
    aplikasi: 'Sajian',
    selamat_datang: 'مرحباً بكم',
    memuat: 'جار التحميل...',
    memproses: 'جار المعالجة...',
    batal: 'إلغاء',
    simpan: 'حفظ',
    tutup: 'إغلاق',
    coba_lagi: 'إعادة المحاولة',
    hapus: 'حذف',
    ubah: 'تعديل',
    konfirmasi: 'تأكيد',
    sukses: 'نجاح',
    gagal: 'فشل',
    kembali: 'رجوع',
    semua: 'الكل',
    cari: 'بحث',
    pilih: 'اختيار',
  },
  navigasi: {
    masuk: 'تسجيل دخول الموظفين',
    kasir: 'الكاشير',
    dapur: 'المطبخ والبار',
    laporan: 'التقارير',
    pengaturan: 'الإعدادات',
    voucher: 'القسائم',
    menu_publik: 'قائمة الطعام الرقمية',
    contoh: 'نماذج العرض',
  },
  masuk: {
    judul: 'تسجيل الدخول للوردية',
    pilih_pegawai: 'اختر اسم الموظف',
    masukkan_pin: 'أدخل رمز PIN المكون من 6 أرقام',
    tombol_masuk: 'دخول',
    ganti_pegawai: 'تغيير الموظف',
    batal_masuk: 'إلغاء الدخول',
    pin_salah: 'رمز PIN غير صحيح أو الجهاز غير مسجل (AU-101).',
    sukses_masuk: 'مرحباً بك في الوردية! تم تنشيط الجلسة.',
  },
  kasir: {
    judul: 'الكاشير والطلبات',
    pilih_meja: 'اختر الطاولة',
    keranjang: 'سلة الطلبات',
    tambah_item: 'إضافة عنصر',
    kurang_item: 'تقليل عنصر',
    batal_item: 'إلغاء عنصر',
    kirim_dapur: 'إرسال إلى المطبخ',
    beri_diskon: 'تطبيق خصم',
    proses_bayar: 'دفع الطلب',
    buka_shift: 'فتح الوردية',
    tutup_shift: 'إغلاق الوردية',
    total_belanja: 'الإجمالي الكلي',
    subtotal: 'المجموع الفرعي',
    pajak: 'ضريبة PB1',
    service: 'رسوم الخدمة',
    diskon: 'الخصم',
    kembalian: 'الباقي',
    uang_diterima: 'المبلغ المستلم',
    metode_tunai: 'نقداً',
    metode_qris: 'QRIS',
    metode_kartu: 'بطاقة مدى/ائتمان',
  },
  dapur: {
    judul: 'شاشة المطبخ والبار',
    antrean_masuk: 'طلبات جديدة',
    sedang_dimasak: 'قيد الطهي',
    siap_saji: 'جاهز للتقديم',
    mulai_masak: 'بدء الطهي',
    selesai_masak: 'تم الانتهاء',
    tandai_habis: 'تحديد كمنتهي',
    ketersediaan_menu: 'حالة الأصناف',
  },
  laporan: {
    judul: 'تقارير المبيعات والنقدية',
    filter_tanggal: 'تصفية حسب التاريخ',
    pilih_cabang: 'اختر الفرع',
    cetak_laporan: 'طباعة التقرير',
    ekspor_data: 'تصدير البيانات',
    omset_penjualan: 'إجمالي المبيعات',
    transaksi_selesai: 'العمليات المكتملة',
    rincian_metode: 'تفاصيل طرق الدفع',
  },
  pengaturan: {
    judul: 'إعدادات المطعم',
    pajak_service: 'المالية والضرائب',
    tata_letak_meja: 'تخطيط الطاولات',
    pegawai_izin: 'الموظفون والصلاحيات',
    simpan_pajak: 'حفظ الضرائب والخدمة',
    simpan_tema: 'تطبيق السمة',
    tambah_meja: 'إضافة طاولة',
    hapus_meja: 'حذف طاولة',
    tambah_pegawai: 'إضافة موظف',
    ubah_izin: 'تحديث الصلاحيات',
  },
  voucher: {
    judul: 'القسائم والعروض',
    masukkan_kode: 'أدخل رمز القسيمة',
    periksa_voucher: 'التحقق من القسيمة',
    klaim_diskon: 'تطبيق القسيمة',
    voucher_valid: 'القسيمة صالحة.',
    voucher_tidak_valid: 'القسيمة غير صالحة أو تم استخدامها مسبقاً.',
  },
  pelanggan: {
    judul: 'قائمة الطعام الرقمية',
    cari_menu: 'ابحث عن وجبات شهية...',
    semua_kategori: 'جميع الفئات',
    makanan: 'مأكولات',
    minuman: 'مشروبات',
    camilan: 'وجبات خفيفة',
    habis: 'نفد',
  },
  keadaan: {
    kosong_judul: 'لا توجد بيانات',
    kosong_keterangan: 'لا توجد طلبات أو عناصر في هذه الصفحة حالياً.',
    memuat_judul: 'جار تحميل البيانات...',
    gagal_judul: 'فشل تحميل البيانات',
    gagal_keterangan: 'يرجى التحقق من اتصال الإنترنت والمحاولة مرة أخرى.',
    menunggu_terkirim: 'في انتظار الإرسال إلى الخادم',
    tanpa_akses: 'ليس لديك صلاحية للوصول إلى هذه الصفحة.',
    data_sebagian: 'عرض البيانات المحفوظة محلياً.',
    berhasil_disimpan: 'تم حفظ البيانات بنجاح.',
  },
}
