import type { KamusBahasa } from './id'

/**
 * قاموس اللغة العربية (ar) — Arabic Translation Dictionary
 */
export const ar: KamusBahasa = {
  umum: {
    aplikasi: 'Sajian',
    selamat_datang: 'مرحباً بكم',
    memuat: 'جار التحميل...',
    memproses: 'جار المعالجة...',
    batal: 'إلغاء',
    simpan: 'حفظ',
    tutup: 'إغلاق',
    selesai: 'تم',
    coba_lagi: 'إعادة المحاولة',
    hapus: 'حذف',
    ubah: 'تعديل',
    konfirmasi: 'تأكيد',
    sukses: 'نجاح',
    gagal: 'فشل',
    kembali: 'رجوع',
    semua: 'الكل',
    cari: 'بحث',
    pilih: 'اختيار',
    keluar: 'تسجيل الخروج',
    bantuan: 'مساعدة',
  },
  navigasi: {
    masuk: 'تسجيل دخول الموظفين',
    kasir: 'الكاشير POS',
    dapur: 'المطبخ والبار',
    laporan: 'التقارير والنقدية',
    pengaturan: 'الإعدادات',
    voucher: 'القسائم',
    menu_publik: 'قائمة الطعام الرقمية',
    contoh: 'نماذج العرض',
    menu_stok: 'القائمة والمخزون',
    pegawai: 'إدارة الموظفين',
    riwayat: 'سجل المعاملات',
    tutup_kas: 'إغلاق وردية النقد',
    pesanan_meja: 'طلبات الطاولات',
    status_pesanan: 'حالة الطلب',
    stok_habis: 'تحديد كمنتهي',
    katalog: 'دليل القائمة',
    voucher_saya: 'قسائمي',
    dasbor_platform: 'لوحة التحكم',
    resto_penyewa: 'المطاعم المشتركة',
    mode_dukungan: 'وضع الدعم',
  },
  masuk: {
    judul: 'تسجيل الدخول للوردية',
    pilih_pegawai: 'اختر اسم الموظف',
    masukkan_pin: 'أدخل رمز PIN المكون من 6 أرقام',
    tombol_masuk: 'دخول',
    ganti_pegawai: 'تغيير الموظف',
    batal_masuk: 'إلغاء الدخول',
    pin_salah: 'رمز PIN غير صحيح أو الجهاز غير مسجل (AU-101).',
    sukses_masuk: 'مرحباً بك في الوردية! تم تنشيط الجلسة.',
  },
  kasir: {
    judul: 'الكاشير والطلبات',
    pilih_meja: 'اختر الطاولة',
    keranjang: 'سلة الطلبات',
    tambah_item: 'إضافة عنصر',
    kurang_item: 'تقليل عنصر',
    batal_item: 'إلغاء عنصر',
    kirim_dapur: 'إرسال إلى المطبخ',
    beri_diskon: 'تطبيق خصم',
    proses_bayar: 'دفع الطلب',
    buka_shift: 'فتح الوردية',
    tutup_shift: 'إغلاق الوردية',
    shift_aktif: 'الوردية النشطة',
    peringatan_belum_buka_kas:
      'لم يقم الكاشير بفتح وردية الصندوق بعد. يرجى فتح الوردية أولاً قبل تنفيذ المعاملات.',
    tombol_buka_kas_cepat: 'فتح الوردية الآن',
    transaksi_wajib_shift: 'لا يمكن معالجة المعاملات إلا بعد فتح وردية الصندوق.',
    pengingat_shift_lewat_tengah_malam:
      'مناوبة الكاشير تجاوزت منتصف الليل! فُتحت بالأمس ولم تُغلق بعد. يُرجى إغلاق المناوبة فوراً.',
    pengingat_shift_lewat_jam_tutup:
      'انتهت ساعات العمل. الوقت الحالي تجاوز وقت إغلاق الكاشير. يُرجى إغلاق المناوبة.',
    pengingat_shift_durasi_panjang:
      'مناوبة الكاشير تعمل منذ أكثر من 12 ساعة. يُرجى التحقق وإجراء إغلاق المناوبة.',
    pengingat_shift_mendekati_tutup:
      'اقترب وقت إغلاق المطعم. يُرجى تجهيز عد النقد الفعلي لإغلاق المناوبة.',
    tombol_tutup_kas_sekarang: 'إغلاق المناوبة الآن',
    tombol_ingatkan_nanti: 'تذكير لاحقاً',
    tagihan_terbuka: 'الفواتير المفتوحة',
    total_belanja: 'الإجمالي الكلي',
    subtotal: 'المجموع الفرعي',
    pajak: 'ضريبة PB1',
    service: 'رسوم الخدمة',
    diskon: 'الخصم',
    kembalian: 'الباقي',
    uang_diterima: 'المبلغ المستلم',
    metode_tunai: 'نقداً',
    metode_qris: 'QRIS',
    metode_kartu: 'بطاقة مدى/ائتمان',
    cari_menu: 'ابحث عن طعام أو شراب...',
    semua_menu: 'جميع الأطباق',
    makanan_utama: 'الأطباق الرئيسية',
    minuman_segar: 'المشروبات',
    cemilan_pendamping: 'المقبلات والوجبات الخفيفة',
    favorit: 'مفضل',
    habis: 'نفد',
    tipe_dinein: 'تناول في المطعم (Dine In)',
    tipe_takeaway: 'طلب سفري (Takeaway)',
    tipe_ojol: 'توصيل إلكتروني (Ojol)',
    pilih_meja_judul: 'اختر الطاولة ونوع الطلب',
    meja_kosong: 'فارغة',
    meja_terisi: 'مشغولة',
    meja_siap: 'جاهزة',
    tamu: 'ضيوف',
    catatan_khusus: 'ملاحظات سريعة للطلب',
    catatan_dapur: 'ملاحظات إضافية للمطبخ',
    selesai_lanjutkan: 'تم والمتابعة',
    opsi_item: 'تحديد الخيارات',
    harga_dasar: 'السعر الأساسي',
    varian_ukuran: 'النوع / الحجم',
    tambahan_topping: 'إضافات (اختياري)',
    tambah_ke_pesanan: 'إضافة إلى الطلب',
    keranjang_kosong: 'لا توجد طلبات بعد',
    keranjang_kosong_petunjuk: 'اختر عناصر من القائمة لإضافتها إلى الطلب.',
    uang_pas: 'المبلغ بالضبط',
    alasan_selisih_label: 'سبب فرق النقدية',
    kas_pergerakan: 'حركة النقد (إيداع/صرف)',
    kas_pergerakan_judul: 'تسجيل حركة النقد',
    kas_pergerakan_petunjuk: 'تسجيل النقد الداخل والخارج بخلاف المبيعات.',
    jenis_kas: 'نوع الحركة',
    kas_masuk: 'نقد وارد (إضافة عهدة)',
    kas_keluar: 'نقد خارج (مصروفات تشغيل)',
    kas_setoran: 'إيداع في الخزينة/البنك',
    kas_koreksi: 'تصحيح النقدية',
    nominal_kas: 'المبلغ (روبية)',
    alasan_kas: 'السبب / الغرض (إلزامي)',
    alasan_kas_placeholder: 'اكتب سبب خروج أو دخول النقد...',
    disetujui_oleh_label: 'تمت الموافقة من (اختياري)',
    simpan_kas: 'حفظ حركة النقد',
    sukses_kas_pergerakan: 'تم تسجيل حركة النقد بنجاح.',
    koreksi_modal: 'تصحيح الرصيد الافتتاحي',
    koreksi_modal_judul: 'تصحيح عهدة بداية الوردية',
    koreksi_modal_petunjuk: 'يمكن تصحيح خطأ العهدة الافتتاحية بموافقة المشرف دون حذف البيانات.',
    modal_awal_saat_ini: 'العهدة الافتتاحية الحالية',
    modal_awal_baru: 'العهدة الافتتاحية الجديدة (Rp)',
    selisih_koreksi: 'فارق التصحيح',
    alasan_koreksi_modal: 'سبب التصحيح (إلزامي)',
    alasan_koreksi_placeholder: 'اكتب سبب تصحيح العهدة الافتتاحية...',
    penyetuju_atasan: 'المشرف المعتمد',
    pilih_atasan: 'اختر المشرف',
    pin_atasan: 'رمز المشرف (PIN)',
    pin_atasan_petunjuk: 'يجب إدخاله من قبل المشرف المخول.',
    simpan_koreksi_modal: 'حفظ تصحيح العهدة',
    sukses_koreksi_modal: 'تم تصحيح العهدة الافتتاحية بنجاح.',
  },
  dapur: {
    judul: 'شاشة المطبخ والبار',
    antrean_masuk: 'طلبات جديدة',
    sedang_dimasak: 'قيد الطهي',
    siap_saji: 'جاهز للتقديم',
    mulai_masak: 'بدء الطهي',
    selesai_masak: 'تم الانتهاء',
    tandai_habis: 'تحديد كمنتهي',
    ketersediaan_menu: 'حالة الأصناف',
  },
  laporan: {
    judul: 'تقارير المبيعات والنقدية',
    filter_tanggal: 'تصفية حسب التاريخ',
    pilih_cabang: 'اختر الفرع',
    cetak_laporan: 'طباعة التقرير',
    ekspor_data: 'تصدير البيانات',
    omset_penjualan: 'إجمالي المبيعات',
    transaksi_selesai: 'العمليات المكتملة',
    rincian_metode: 'تفاصيل طرق الدفع',
    kas_harian: 'النقد اليومي',
    kas_shift: 'نقد الوردية',
    modal_awal: 'الرصيد الافتتاحي',
    kas_masuk: 'نقد وارد',
    kas_keluar: 'نقد صادر',
    setoran: 'إيداع بنكي',
    uang_seharusnya: 'النقد المتوقع',
    uang_fisik: 'النقد الفعلي',
    selisih: 'فارق النقدية',
    alasan_selisih: 'سبب الفارق',
    omzet_makanan: 'مبيعات الأطعمة',
    omzet_minuman: 'مبيعات المشروبات',
    omzet_lainnya: 'مبيعات أخرى',
    total_diskon: 'الخصومات والقسائم',
    total_pembatalan: 'الطلبات الملغاة',
    kerugian_pembatalan: 'قيمة الخسارة',
    kasir_buka: 'كاشير الافتتاح',
    kasir_tutup: 'كاشير الإغلاق',
    jam_shift: 'ساعات الوردية',
    status_shift: 'حالة الوردية',
    semua_cabang: 'جميع الفروع',
    tutup_detail: 'إغلاق التفاصيل',
    rincian_shift: 'تفاصيل الوردية',
    tab_penjualan: 'المبيعات',
    tab_kas: 'النقد والورديات',
    omzet_kategori: 'الإيرادات حسب الفئة',
    tren_harian: 'اتجاه المبيعات اليومية',
    rentang_tanggal: 'نطاق التاريخ',
    tanggal_mulai: 'تاريخ البدء',
    tanggal_akhir: 'تاريخ الانتهاء',
    terapkan_filter: 'تطبيق',
    batas_90_hari: 'الحد الأقصى لنطاق التاريخ هو 90 يومًا.',
    rata_rata_transaksi: 'متوسط المعاملة',
    total_subtotal: 'إجمالي المجموع الفرعي',
    total_pajak: 'إجمالي الضريبة',
    total_service: 'إجمالي الخدمة',
    jumlah_transaksi: 'عدد المعاملات',
    qty_terjual: 'الحصص المباعة',
    persentase: 'النسبة',
    tanpa_kategori: 'بدون فئة',
    tidak_ada_data: 'لا توجد بيانات مبيعات لهذه الفترة.',
    muat_ulang: 'إعادة التحميل',
  },
  pengaturan: {
    judul: 'إعدادات المطعم',
    pajak_service: 'المالية والضرائب',
    tata_letak_meja: 'تخطيط الطاولات',
    pegawai_izin: 'الموظفون والصلاحيات',
    simpan_pajak: 'حفظ الضرائب والخدمة',
    simpan_tema: 'تطبيق السمة',
    tambah_meja: 'إضافة طاولة',
    hapus_meja: 'حذف طاولة',
    tambah_pegawai: 'إضافة موظف',
    ubah_izin: 'تحديث الصلاحيات',
  },
  voucher: {
    judul: 'القسائم والعروض',
    masukkan_kode: 'أدخل رمز القسيمة',
    periksa_voucher: 'التحقق من القسيمة',
    klaim_diskon: 'تطبيق القسيمة',
    voucher_valid: 'القسيمة صالحة.',
    voucher_tidak_valid: 'القسيمة غير صالحة أو تم استخدامها مسبقاً.',
  },
  pelanggan: {
    judul: 'قائمة الطعام الرقمية',
    cari_menu: 'ابحث عن وجبات شهية...',
    semua_kategori: 'جميع الفئات',
    makanan: 'مأكولات',
    minuman: 'مشروبات',
    camilan: 'وجبات خفيفة',
    habis: 'نفد',
  },
  keadaan: {
    kosong_judul: 'لا توجد بيانات',
    kosong_keterangan: 'لا توجد طلبات أو عناصر في هذه الصفحة حالياً.',
    memuat_judul: 'جار تحميل البيانات...',
    gagal_judul: 'فشل تحميل البيانات',
    gagal_keterangan: 'يرجى التحقق من اتصال الإنترنت والمحاولة مرة أخرى.',
    menunggu_terkirim: 'في انتظار الإرسال إلى الخادم',
    tanpa_akses: 'ليس لديك صلاحية للوصول إلى هذه الصفحة.',
    data_sebagian: 'عرض البيانات المحفوظة محلياً.',
    berhasil_disimpan: 'تم حفظ البيانات بنجاح.',
  },
  contoh: {
    judul_halaman: 'عرض المكونات · المرحلة 0 و 1C',
    keterangan_selamat: 'الكاشير والمطبخ والتقارير والعملاء في مكان واحد.',
    kartu_tombol: 'الأزرار',
    kartu_lencana: 'الشارات',
    kartu_kolom_isian: 'حقول الإدخال',
    kartu_tabel: 'جدول الطلبات',
    ragam_5: '5 أنماط',
    tombol_tahan: 'تثبيت',
    tombol_kecil: 'صغير',
    tombol_polos: 'بسيط',
    tombol_nonaktif: 'معطل حالياً',
    tombol_lebar: 'عرض كامل',
    lencana_aksen: 'لون مميز',
    lencana_lunas: 'مدفوع',
    lencana_belum_bayar: 'غير مدفوع',
    lencana_dibatalkan: 'ملغى',
    lencana_dibungkus: 'مغلف',
    lencana_netral: 'محايد',
    nama_pelanggan: 'اسم العميل',
    contoh_nama: 'مثال: أحمد',
    boleh_kosong: 'اختياري.',
    nomor_meja: 'رقم الطاولة',
    galat_meja: 'رقم الطاولة مطلوب.',
    pemberitahuan_pesan: 'إشعار توضيحي: تم حفظ طلب الطاولة 3.',
    tampilkan_pemberitahuan: 'إظهار الإشعار مجدداً',
  },
}
