import type { KamusBahasa } from './id'

/**
 * English Translation Dictionary (en)
 */
export const en: KamusBahasa = {
  umum: {
    aplikasi: 'Sajian',
    selamat_datang: 'Welcome',
    memuat: 'Loading...',
    memproses: 'Processing...',
    batal: 'Cancel',
    simpan: 'Save',
    tutup: 'Close',
    selesai: 'Done',
    coba_lagi: 'Try Again',
    hapus: 'Delete',
    ubah: 'Edit',
    konfirmasi: 'Confirm',
    sukses: 'Success',
    gagal: 'Failed',
    kembali: 'Back',
    semua: 'All',
    cari: 'Search',
    pilih: 'Select',
    keluar: 'Log Out',
    bantuan: 'Help',
  },
  navigasi: {
    masuk: 'Staff Login',
    kasir: 'Cashier POS',
    dapur: 'Kitchen & Bar',
    laporan: 'Reports & Cash',
    pengaturan: 'Settings',
    voucher: 'Vouchers',
    menu_publik: 'Digital Menu',
    contoh: 'Component Demo',
    menu_stok: 'Menu & Stock',
    pegawai: 'Staff Management',
    riwayat: 'Transaction History',
    tutup_kas: 'Close Shift Cash',
    pesanan_meja: 'Table Orders',
    status_pesanan: 'Order Status',
    stok_habis: 'Mark Sold Out',
    katalog: 'Menu Catalog',
    voucher_saya: 'My Vouchers',
    dasbor_platform: 'Platform Dashboard',
    resto_penyewa: 'Tenant Restaurants',
    mode_dukungan: 'Support Mode',
  },
  masuk: {
    judul: 'Staff Duty Login',
    pilih_pegawai: 'Select Staff Name',
    masukkan_pin: 'Enter 6-Digit PIN',
    tombol_masuk: 'Log In',
    ganti_pegawai: 'Change Staff',
    batal_masuk: 'Cancel Login',
    pin_salah: 'Incorrect PIN or unregistered device (AU-101).',
    sukses_masuk: 'Welcome on duty! Active session started.',
  },
  kasir: {
    judul: 'Cashier & POS',
    pilih_meja: 'Select Table',
    keranjang: 'Order Cart',
    tambah_item: 'Add Item',
    kurang_item: 'Decrease Item',
    batal_item: 'Void Item',
    kirim_dapur: 'Send to Kitchen',
    beri_diskon: 'Apply Discount',
    proses_bayar: 'Pay Order',
    buka_shift: 'Open Shift',
    tutup_shift: 'Close Shift',
    shift_aktif: 'Active Shift',
    peringatan_belum_buka_kas:
      'Cashier has not opened a cash shift. Please open cash register before processing transactions.',
    tombol_buka_kas_cepat: 'Open Shift Now',
    transaksi_wajib_shift: 'Transactions can only be processed after opening a cashier shift.',
    tagihan_terbuka: 'Open Bills',
    total_belanja: 'Grand Total',
    subtotal: 'Subtotal',
    pajak: 'Tax (PB1)',
    service: 'Service Charge',
    diskon: 'Discount',
    kembalian: 'Change',
    uang_diterima: 'Cash Received',
    metode_tunai: 'Cash',
    metode_qris: 'QRIS',
    metode_kartu: 'Debit/Credit Card',
    cari_menu: 'Search food or beverage...',
    semua_menu: 'All Menu',
    makanan_utama: 'Mains',
    minuman_segar: 'Beverages',
    cemilan_pendamping: 'Sides & Snacks',
    favorit: 'Favorite',
    habis: 'Sold Out',
    tipe_dinein: 'Dine In',
    tipe_takeaway: 'Takeaway',
    tipe_ojol: 'Online Delivery',
    pilih_meja_judul: 'Select Table & Order Type',
    meja_kosong: 'Available',
    meja_terisi: 'Occupied',
    meja_siap: 'Ready',
    tamu: 'Guests',
    catatan_khusus: 'Quick Order Notes',
    catatan_dapur: 'Additional Kitchen Notes',
    selesai_lanjutkan: 'Done & Continue',
    opsi_item: 'Select Options',
    harga_dasar: 'Base Price',
    varian_ukuran: 'Variant / Size Option',
    tambahan_topping: 'Toppings (Optional)',
    tambah_ke_pesanan: 'Add to Order',
    keranjang_kosong: 'No orders yet',
    keranjang_kosong_petunjuk: 'Select menu items on the left to add.',
    uang_pas: 'Exact Cash',
    alasan_selisih_label: 'Cash Variance Reason',
    kas_pergerakan: 'Cash In & Out',
    kas_pergerakan_judul: 'Cash Movement Record',
    kas_pergerakan_petunjuk: 'Record cash moving in or out outside sales.',
    jenis_kas: 'Movement Type',
    kas_masuk: 'Cash In (Add Float)',
    kas_keluar: 'Cash Out (Expense)',
    kas_setoran: 'Safe/Bank Deposit',
    kas_koreksi: 'Cash Correction',
    nominal_kas: 'Amount (Rp)',
    alasan_kas: 'Reason / Purpose (Required)',
    alasan_kas_placeholder: 'Enter reason for cash inflow or outflow...',
    disetujui_oleh_label: 'Approved By (Optional)',
    simpan_kas: 'Save Cash Movement',
    sukses_kas_pergerakan: 'Cash movement successfully recorded.',
  },
  dapur: {
    judul: 'Kitchen & Bar Display',
    antrean_masuk: 'New Orders',
    sedang_dimasak: 'Cooking',
    siap_saji: 'Ready to Serve',
    mulai_masak: 'Start Cooking',
    selesai_masak: 'Mark Ready',
    tandai_habis: 'Mark Sold Out',
    ketersediaan_menu: 'Menu Availability',
  },
  laporan: {
    judul: 'Sales & Cash Reports',
    filter_tanggal: 'Filter Date',
    pilih_cabang: 'Select Branch',
    cetak_laporan: 'Print Report',
    ekspor_data: 'Export Summary',
    omset_penjualan: 'Total Sales Revenue',
    transaksi_selesai: 'Completed Transactions',
    rincian_metode: 'Payment Method Breakdown',
  },
  pengaturan: {
    judul: 'Restaurant Settings',
    pajak_service: 'Finance & Tax',
    tata_letak_meja: 'Table Layout',
    pegawai_izin: 'Staff & Permissions',
    simpan_pajak: 'Save Tax & Service',
    simpan_tema: 'Apply Theme',
    tambah_meja: 'Add Table',
    hapus_meja: 'Delete Table',
    tambah_pegawai: 'Add Staff',
    ubah_izin: 'Update Role Permissions',
  },
  voucher: {
    judul: 'Vouchers & Promotions',
    masukkan_kode: 'Enter Voucher Code',
    periksa_voucher: 'Check Voucher',
    klaim_diskon: 'Apply Voucher',
    voucher_valid: 'Voucher is valid.',
    voucher_tidak_valid: 'Voucher is invalid or already redeemed.',
  },
  pelanggan: {
    judul: 'Digital Menu',
    cari_menu: 'Search delicious menu...',
    semua_kategori: 'All Categories',
    makanan: 'Food',
    minuman: 'Drinks',
    camilan: 'Snacks',
    habis: 'Sold Out',
  },
  keadaan: {
    kosong_judul: 'No Data Yet',
    kosong_keterangan: 'There are no active orders or items in this view.',
    memuat_judul: 'Loading Data...',
    gagal_judul: 'Failed to Load Data',
    gagal_keterangan: 'Please check your internet connection and try again.',
    menunggu_terkirim: 'Queued for Sync with Server',
    tanpa_akses: 'You do not have permission to access this page.',
    data_sebagian: 'Displaying cached local data.',
    berhasil_disimpan: 'Data saved successfully.',
  },
  contoh: {
    judul_halaman: 'Component Demo · Phase 0 & 1C',
    keterangan_selamat: 'Cashier, kitchen, reports, and customers in one place.',
    kartu_tombol: 'Buttons',
    kartu_lencana: 'Badges',
    kartu_kolom_isian: 'Input Fields',
    kartu_tabel: 'Order Table',
    ragam_5: '5 variants',
    tombol_tahan: 'Hold',
    tombol_kecil: 'Small',
    tombol_polos: 'Plain',
    tombol_nonaktif: 'Disabled',
    tombol_lebar: 'Full Width',
    lencana_aksen: 'Accent',
    lencana_lunas: 'Paid',
    lencana_belum_bayar: 'Unpaid',
    lencana_dibatalkan: 'Cancelled',
    lencana_dibungkus: 'Takeaway',
    lencana_netral: 'Neutral',
    nama_pelanggan: 'Customer Name',
    contoh_nama: 'e.g. John',
    boleh_kosong: 'Optional.',
    nomor_meja: 'Table Number',
    galat_meja: 'Table number is required.',
    pemberitahuan_pesan: 'Notice demo: table 3 order saved.',
    tampilkan_pemberitahuan: 'Show notification again',
  },
}
