import type { KamusBahasa } from './id'

/**
 * English Translation Dictionary (en)
 */
export const en: KamusBahasa = {
  umum: {
    aplikasi: 'Sajian',
    selamat_datang: 'Welcome',
    memuat: 'Loading...',
    memproses: 'Processing...',
    batal: 'Cancel',
    simpan: 'Save',
    tutup: 'Close',
    coba_lagi: 'Try Again',
    hapus: 'Delete',
    ubah: 'Edit',
    konfirmasi: 'Confirm',
    sukses: 'Success',
    gagal: 'Failed',
    kembali: 'Back',
    semua: 'All',
    cari: 'Search',
    pilih: 'Select',
  },
  navigasi: {
    masuk: 'Staff Login',
    kasir: 'Cashier',
    dapur: 'Kitchen & Bar',
    laporan: 'Reports',
    pengaturan: 'Settings',
    voucher: 'Vouchers',
    menu_publik: 'Digital Menu',
    contoh: 'Component Demo',
  },
  masuk: {
    judul: 'Staff Duty Login',
    pilih_pegawai: 'Select Staff Name',
    masukkan_pin: 'Enter 6-Digit PIN',
    tombol_masuk: 'Log In',
    ganti_pegawai: 'Change Staff',
    batal_masuk: 'Cancel Login',
    pin_salah: 'Incorrect PIN or unregistered device (AU-101).',
    sukses_masuk: 'Welcome on duty! Active session started.',
  },
  kasir: {
    judul: 'Cashier & POS',
    pilih_meja: 'Select Table',
    keranjang: 'Order Cart',
    tambah_item: 'Add Item',
    kurang_item: 'Decrease Item',
    batal_item: 'Void Item',
    kirim_dapur: 'Send to Kitchen',
    beri_diskon: 'Apply Discount',
    proses_bayar: 'Pay Order',
    buka_shift: 'Open Shift',
    tutup_shift: 'Close Shift',
    total_belanja: 'Grand Total',
    subtotal: 'Subtotal',
    pajak: 'Tax (PB1)',
    service: 'Service Charge',
    diskon: 'Discount',
    kembalian: 'Change',
    uang_diterima: 'Cash Received',
    metode_tunai: 'Cash',
    metode_qris: 'QRIS',
    metode_kartu: 'Debit/Credit Card',
  },
  dapur: {
    judul: 'Kitchen & Bar Display',
    antrean_masuk: 'New Orders',
    sedang_dimasak: 'Cooking',
    siap_saji: 'Ready to Serve',
    mulai_masak: 'Start Cooking',
    selesai_masak: 'Mark Ready',
    tandai_habis: 'Mark Sold Out',
    ketersediaan_menu: 'Menu Availability',
  },
  laporan: {
    judul: 'Sales & Cash Reports',
    filter_tanggal: 'Filter Date',
    pilih_cabang: 'Select Branch',
    cetak_laporan: 'Print Report',
    ekspor_data: 'Export Summary',
    omset_penjualan: 'Total Sales Revenue',
    transaksi_selesai: 'Completed Transactions',
    rincian_metode: 'Payment Method Breakdown',
  },
  pengaturan: {
    judul: 'Restaurant Settings',
    pajak_service: 'Finance & Tax',
    tata_letak_meja: 'Table Layout',
    pegawai_izin: 'Staff & Permissions',
    simpan_pajak: 'Save Tax & Service',
    simpan_tema: 'Apply Theme',
    tambah_meja: 'Add Table',
    hapus_meja: 'Delete Table',
    tambah_pegawai: 'Add Staff',
    ubah_izin: 'Update Role Permissions',
  },
  voucher: {
    judul: 'Vouchers & Promotions',
    masukkan_kode: 'Enter Voucher Code',
    periksa_voucher: 'Check Voucher',
    klaim_diskon: 'Apply Voucher',
    voucher_valid: 'Voucher is valid.',
    voucher_tidak_valid: 'Voucher is invalid or already redeemed.',
  },
  pelanggan: {
    judul: 'Digital Menu',
    cari_menu: 'Search delicious menu...',
    semua_kategori: 'All Categories',
    makanan: 'Food',
    minuman: 'Drinks',
    camilan: 'Snacks',
    habis: 'Sold Out',
  },
  keadaan: {
    kosong_judul: 'No Data Yet',
    kosong_keterangan: 'There are no active orders or items in this view.',
    memuat_judul: 'Loading Data...',
    gagal_judul: 'Failed to Load Data',
    gagal_keterangan: 'Please check your internet connection and try again.',
    menunggu_terkirim: 'Queued for Sync with Server',
    tanpa_akses: 'You do not have permission to access this page.',
    data_sebagian: 'Displaying cached local data.',
    berhasil_disimpan: 'Data saved successfully.',
  },
}
