/**
 * Kamus Bahasa Indonesia (id) — Sumber Kebenaran Teks UI
 */
export const id = {
  umum: {
    aplikasi: 'Sajian',
    selamat_datang: 'Selamat Datang',
    memuat: 'Memuat...',
    memproses: 'Memproses...',
    batal: 'Batal',
    simpan: 'Simpan',
    tutup: 'Tutup',
    coba_lagi: 'Coba Lagi',
    hapus: 'Hapus',
    ubah: 'Ubah',
    konfirmasi: 'Konfirmasi',
    sukses: 'Berhasil',
    gagal: 'Gagal',
    kembali: 'Kembali',
    semua: 'Semua',
    cari: 'Cari',
    pilih: 'Pilih',
  },
  navigasi: {
    masuk: 'Masuk Pegawai',
    kasir: 'Kasir',
    dapur: 'Dapur & Bar',
    laporan: 'Laporan',
    pengaturan: 'Pengaturan',
    voucher: 'Voucher',
    menu_publik: 'Menu Digital',
    contoh: 'Contoh Komponen',
  },
  masuk: {
    judul: 'Masuk Bertugas',
    pilih_pegawai: 'Pilih Nama Pegawai',
    masukkan_pin: 'Masukkan 6 Digit PIN',
    tombol_masuk: 'Masuk',
    ganti_pegawai: 'Ganti Pegawai',
    batal_masuk: 'Batal Masuk',
    pin_salah: 'PIN salah atau perangkat belum terdaftar (AU-101).',
    sukses_masuk: 'Selamat bertugas! Sesi masuk aktif.',
  },
  kasir: {
    judul: 'Kasir & Transaksi',
    pilih_meja: 'Pilih Meja',
    keranjang: 'Keranjang Pesanan',
    tambah_item: 'Tambah Item',
    kurang_item: 'Kurangi Item',
    batal_item: 'Batalkan Item',
    kirim_dapur: 'Kirim ke Dapur',
    beri_diskon: 'Beri Diskon',
    proses_bayar: 'Bayar Pesanan',
    buka_shift: 'Buka Shift',
    tutup_shift: 'Tutup Shift',
    total_belanja: 'Total Belanja',
    subtotal: 'Subtotal',
    pajak: 'PB1',
    service: 'Biaya Layanan',
    diskon: 'Potongan Diskon',
    kembalian: 'Kembalian',
    uang_diterima: 'Uang Diterima',
    metode_tunai: 'Tunai',
    metode_qris: 'QRIS',
    metode_kartu: 'Kartu Debit/Kredit',
  },
  dapur: {
    judul: 'Pesanan Dapur & Bar',
    antrean_masuk: 'Pesanan Baru',
    sedang_dimasak: 'Sedang Dimasak',
    siap_saji: 'Siap Disajikan',
    mulai_masak: 'Mulai Masak',
    selesai_masak: 'Siap Saji',
    tandai_habis: 'Tandai Habis',
    ketersediaan_menu: 'Ketersediaan Menu',
  },
  laporan: {
    judul: 'Laporan Penjualan & Kas',
    filter_tanggal: 'Filter Tanggal',
    pilih_cabang: 'Pilih Cabang',
    cetak_laporan: 'Cetak Laporan',
    ekspor_data: 'Ekspor Ringkasan',
    omset_penjualan: 'Total Omset Penjualan',
    transaksi_selesai: 'Transaksi Selesai',
    rincian_metode: 'Rincian Metode Bayar',
  },
  pengaturan: {
    judul: 'Pengaturan Resto',
    pajak_service: 'Keuangan & Pajak',
    tata_letak_meja: 'Tata Letak Meja',
    pegawai_izin: 'Pegawai & Hak Izin',
    simpan_pajak: 'Simpan Pajak & Service',
    simpan_tema: 'Terapkan Tema',
    tambah_meja: 'Tambah Meja',
    hapus_meja: 'Hapus Meja',
    tambah_pegawai: 'Tambah Pegawai',
    ubah_izin: 'Ubah Izin Peran',
  },
  voucher: {
    judul: 'Voucher & Diskon',
    masukkan_kode: 'Masukkan Kode Voucher',
    periksa_voucher: 'Periksa Voucher',
    klaim_diskon: 'Terapkan Voucher',
    voucher_valid: 'Voucher valid.',
    voucher_tidak_valid: 'Voucher tidak valid atau sudah digunakan.',
  },
  pelanggan: {
    judul: 'Menu Digital',
    cari_menu: 'Cari menu lezat...',
    semua_kategori: 'Semua Kategori',
    makanan: 'Makanan',
    minuman: 'Minuman',
    camilan: 'Camilan',
    habis: 'Habis',
  },
  keadaan: {
    kosong_judul: 'Belum Ada Data',
    kosong_keterangan: 'Belum ada data transaksi atau item pada bagian ini.',
    memuat_judul: 'Memuat Data...',
    gagal_judul: 'Gagal Memuat Data',
    gagal_keterangan: 'Periksa sambungan internet lalu coba lagi.',
    menunggu_terkirim: 'Menunggu Pengiriman ke Peladen',
    tanpa_akses: 'Anda tidak memiliki hak akses untuk membuka halaman ini.',
    data_sebagian: 'Menampilkan data yang tersimpan di perangkat.',
    berhasil_disimpan: 'Data berhasil disimpan.',
  },
} as const

export type DeepString<T> = {
  [K in keyof T]: T[K] extends object ? DeepString<T[K]> : string
}

export type KamusBahasa = DeepString<typeof id>
