/**
 * Kamus Bahasa Indonesia (id) — Sumber Kebenaran Teks UI
 */
export const id = {
  umum: {
    aplikasi: 'Sajian',
    selamat_datang: 'Selamat Datang',
    memuat: 'Memuat...',
    memproses: 'Memproses...',
    batal: 'Batal',
    simpan: 'Simpan',
    tutup: 'Tutup',
    selesai: 'Selesai',
    coba_lagi: 'Coba Lagi',
    hapus: 'Hapus',
    ubah: 'Ubah',
    konfirmasi: 'Konfirmasi',
    sukses: 'Berhasil',
    gagal: 'Gagal',
    kembali: 'Kembali',
    semua: 'Semua',
    cari: 'Cari',
    pilih: 'Pilih',
    keluar: 'Keluar',
    bantuan: 'Bantuan',
  },
  navigasi: {
    masuk: 'Masuk Pegawai',
    kasir: 'Kasir POS',
    dapur: 'Dapur & Bar',
    laporan: 'Laporan & Kas',
    pengaturan: 'Pengaturan',
    voucher: 'Voucher',
    menu_publik: 'Menu Digital',
    contoh: 'Contoh Komponen',
    menu_stok: 'Menu & Stok',
    pegawai: 'Kelola Pegawai',
    riwayat: 'Riwayat Transaksi',
    tutup_kas: 'Tutup Kas Shift',
    pesanan_meja: 'Pesanan Meja',
    status_pesanan: 'Status Pesanan',
    stok_habis: 'Tandai Stok Habis',
    katalog: 'Katalog Menu',
    voucher_saya: 'Voucher Saya',
    dasbor_platform: 'Dasbor Platform',
    resto_penyewa: 'Resto Penyewa',
    mode_dukungan: 'Mode Dukungan',
  },
  masuk: {
    judul: 'Masuk Bertugas',
    pilih_pegawai: 'Pilih Nama Pegawai',
    masukkan_pin: 'Masukkan 6 Digit PIN',
    tombol_masuk: 'Masuk',
    ganti_pegawai: 'Ganti Pegawai',
    batal_masuk: 'Batal Masuk',
    pin_salah: 'PIN salah atau perangkat belum terdaftar (AU-101).',
    sukses_masuk: 'Selamat bertugas! Sesi masuk aktif.',
  },
  kasir: {
    judul: 'Kasir & Transaksi',
    pilih_meja: 'Pilih Meja',
    keranjang: 'Keranjang Pesanan',
    tambah_item: 'Tambah Item',
    kurang_item: 'Kurangi Item',
    batal_item: 'Batalkan Item',
    kirim_dapur: 'Kirim ke Dapur',
    beri_diskon: 'Beri Diskon',
    proses_bayar: 'Bayar Pesanan',
    buka_shift: 'Buka Kas',
    tutup_shift: 'Tutup Kas',
    shift_aktif: 'Shift Aktif',
    tagihan_terbuka: 'Tagihan Terbuka',
    total_belanja: 'Total Belanja',
    subtotal: 'Subtotal',
    pajak: 'PB1',
    service: 'Biaya Layanan',
    diskon: 'Potongan Diskon',
    kembalian: 'Kembalian',
    uang_diterima: 'Uang Diterima',
    metode_tunai: 'Tunai',
    metode_qris: 'QRIS',
    metode_kartu: 'Kartu Debit/Kredit',
    cari_menu: 'Cari nama makanan atau minuman...',
    semua_menu: 'Semua Menu',
    makanan_utama: 'Makanan Utama',
    minuman_segar: 'Minuman Segar',
    cemilan_pendamping: 'Cemilan & Pendamping',
    favorit: 'Favorit',
    habis: 'Habis',
    tipe_dinein: 'Makan di Tempat (Dine In)',
    tipe_takeaway: 'Bawa Pulang (Takeaway)',
    tipe_ojol: 'Ojek Online (GoFood/Grab)',
    pilih_meja_judul: 'Pilih Meja & Tipe Pesanan',
    meja_kosong: 'Kosong',
    meja_terisi: 'Terisi',
    meja_siap: 'Siap',
    tamu: 'Tamu',
    catatan_khusus: 'Catatan Khusus Pesanan (Cepat)',
    catatan_dapur: 'Catatan Tambahan untuk Dapur',
    selesai_lanjutkan: 'Selesai & Lanjutkan',
    opsi_item: 'Pilih Opsi',
    harga_dasar: 'Harga Dasar',
    varian_ukuran: 'Pilihan Varian / Ukuran',
    tambahan_topping: 'Tambahan / Topping (Opsional)',
    tambah_ke_pesanan: 'Tambahkan ke Pesanan',
    keranjang_kosong: 'Keranjang Masih Kosong',
    keranjang_kosong_petunjuk: 'Pilih menu di samping untuk menambahkan item ke pesanan.',
    uang_pas: 'Uang Pas',
    alasan_selisih_label: 'Alasan Selisih Kas',
    kas_pergerakan: 'Kas Masuk & Keluar',
    kas_pergerakan_judul: 'Pencatatan Pergerakan Kas',
    kas_pergerakan_petunjuk: 'Catat kas masuk/keluar di luar penjualan.',
    jenis_kas: 'Jenis Pergerakan',
    kas_masuk: 'Kas Masuk (Tambah Modal)',
    kas_keluar: 'Kas Keluar (Operasional)',
    kas_setoran: 'Setoran ke Brankas/Bank',
    kas_koreksi: 'Koreksi Kas',
    nominal_kas: 'Jumlah Uang (Rp)',
    alasan_kas: 'Alasan / Keperluan (Wajib)',
    alasan_kas_placeholder: 'Tuliskan alasan pengeluaran / pemasukan uang kas...',
    disetujui_oleh_label: 'Disetujui Oleh (Opsional)',
    simpan_kas: 'Simpan Catatan Kas',
    sukses_kas_pergerakan: 'Pergerakan kas berhasil dicatat.',
  },
  dapur: {
    judul: 'Pesanan Dapur & Bar',
    antrean_masuk: 'Pesanan Baru',
    sedang_dimasak: 'Sedang Dimasak',
    siap_saji: 'Siap Disajikan',
    mulai_masak: 'Mulai Masak',
    selesai_masak: 'Siap Saji',
    tandai_habis: 'Tandai Habis',
    ketersediaan_menu: 'Ketersediaan Menu',
  },
  laporan: {
    judul: 'Laporan Penjualan & Kas',
    filter_tanggal: 'Filter Tanggal',
    pilih_cabang: 'Pilih Cabang',
    cetak_laporan: 'Cetak Laporan',
    ekspor_data: 'Ekspor Ringkasan',
    omset_penjualan: 'Total Omset Penjualan',
    transaksi_selesai: 'Transaksi Selesai',
    rincian_metode: 'Rincian Metode Bayar',
  },
  pengaturan: {
    judul: 'Pengaturan Resto',
    pajak_service: 'Keuangan & Pajak',
    tata_letak_meja: 'Tata Letak Meja',
    pegawai_izin: 'Pegawai & Hak Izin',
    simpan_pajak: 'Simpan Pajak & Service',
    simpan_tema: 'Terapkan Tema',
    tambah_meja: 'Tambah Meja',
    hapus_meja: 'Hapus Meja',
    tambah_pegawai: 'Tambah Pegawai',
    ubah_izin: 'Ubah Izin Peran',
  },
  voucher: {
    judul: 'Voucher & Diskon',
    masukkan_kode: 'Masukkan Kode Voucher',
    periksa_voucher: 'Periksa Voucher',
    klaim_diskon: 'Terapkan Voucher',
    voucher_valid: 'Voucher valid.',
    voucher_tidak_valid: 'Voucher tidak valid atau sudah digunakan.',
  },
  pelanggan: {
    judul: 'Menu Digital',
    cari_menu: 'Cari menu lezat...',
    semua_kategori: 'Semua Kategori',
    makanan: 'Makanan',
    minuman: 'Minuman',
    camilan: 'Camilan',
    habis: 'Habis',
  },
  keadaan: {
    kosong_judul: 'Belum Ada Data',
    kosong_keterangan: 'Belum ada data transaksi atau item pada bagian ini.',
    memuat_judul: 'Memuat Data...',
    gagal_judul: 'Gagal Memuat Data',
    gagal_keterangan: 'Periksa sambungan internet lalu coba lagi.',
    menunggu_terkirim: 'Menunggu Pengiriman ke Peladen',
    tanpa_akses: 'Anda tidak memiliki hak akses untuk membuka halaman ini.',
    data_sebagian: 'Menampilkan data yang tersimpan di perangkat.',
    berhasil_disimpan: 'Data berhasil disimpan.',
  },
  contoh: {
    judul_halaman: 'Contoh tampilan · Fase 0 & 1C',
    keterangan_selamat: 'Kasir, dapur, laporan, dan pelanggan dalam satu tempat.',
    kartu_tombol: 'Tombol',
    kartu_lencana: 'Lencana',
    kartu_kolom_isian: 'Kolom isian',
    kartu_tabel: 'Tabel pesanan',
    ragam_5: '5 ragam',
    tombol_tahan: 'Tahan',
    tombol_kecil: 'Kecil',
    tombol_polos: 'Polos',
    tombol_nonaktif: 'Sedang nonaktif',
    tombol_lebar: 'Lebar penuh',
    lencana_aksen: 'Aksen',
    lencana_lunas: 'Lunas',
    lencana_belum_bayar: 'Belum dibayar',
    lencana_dibatalkan: 'Dibatalkan',
    lencana_dibungkus: 'Dibungkus',
    lencana_netral: 'Netral',
    nama_pelanggan: 'Nama pelanggan',
    contoh_nama: 'contoh: Budi',
    boleh_kosong: 'Boleh dikosongkan.',
    nomor_meja: 'Nomor meja',
    galat_meja: 'Nomor meja wajib diisi.',
    pemberitahuan_pesan: 'Contoh pemberitahuan: pesanan meja 3 sudah tersimpan.',
    tampilkan_pemberitahuan: 'Tampilkan pemberitahuan lagi',
  },
} as const

export type DeepString<T> = {
  [K in keyof T]: T[K] extends object ? DeepString<T[K]> : string
}

export type KamusBahasa = DeepString<typeof id>
