import type { KamusBahasa } from './id'

/**
 * 简体中文翻译字典 (zh)
 */
export const zh: KamusBahasa = {
  umum: {
    aplikasi: 'Sajian',
    selamat_datang: '欢迎光临',
    memuat: '加载中...',
    memproses: '处理中...',
    batal: '取消',
    simpan: '保存',
    tutup: '关闭',
    coba_lagi: '重试',
    hapus: '删除',
    ubah: '修改',
    konfirmasi: '确认',
    sukses: '成功',
    gagal: '失败',
    kembali: '返回',
    semua: '全部',
    cari: '搜索',
    pilih: '选择',
  },
  navigasi: {
    masuk: '员工登录',
    kasir: '收银台',
    dapur: '厨房出餐',
    laporan: '营业报表',
    pengaturan: '系统设置',
    voucher: '优惠券',
    menu_publik: '电子菜单',
    contoh: '组件示例',
  },
  masuk: {
    judul: '员工上班登录',
    pilih_pegawai: '选择员工姓名',
    masukkan_pin: '输入6位PIN码',
    tombol_masuk: '登录',
    ganti_pegawai: '切换员工',
    batal_masuk: '取消登录',
    pin_salah: 'PIN码错误或设备未注册 (AU-101)。',
    sukses_masuk: '登录成功！工作班次已激活。',
  },
  kasir: {
    judul: '收银与点单',
    pilih_meja: '选择桌号',
    keranjang: '点单列表',
    tambah_item: '增加份数',
    kurang_item: '减少份数',
    batal_item: '退点菜品',
    kirim_dapur: '送入厨房',
    beri_diskon: '给予折扣',
    proses_bayar: '结算订单',
    buka_shift: '开班',
    tutup_shift: '交接班/结班',
    total_belanja: '应付总额',
    subtotal: '小计',
    pajak: '餐饮税 (PB1)',
    service: '服务费',
    diskon: '优惠折扣',
    kembalian: '找零',
    uang_diterima: '实收金额',
    metode_tunai: '现金支付',
    metode_qris: 'QRIS扫码',
    metode_kartu: '刷卡支付',
  },
  dapur: {
    judul: '厨房与吧台显示',
    antrean_masuk: '待制作订单',
    sedang_dimasak: '制作中',
    siap_saji: '已完成/待上菜',
    mulai_masak: '开始制作',
    selesai_masak: '制作完成',
    tandai_habis: '标为售罄',
    ketersediaan_menu: '菜品状态',
  },
  laporan: {
    judul: '销售与收银报表',
    filter_tanggal: '日期筛选',
    pilih_cabang: '选择分店',
    cetak_laporan: '打印报表',
    ekspor_data: '导出数据',
    omset_penjualan: '总营业额',
    transaksi_selesai: '已结账订单',
    rincian_metode: '支付方式明细',
  },
  pengaturan: {
    judul: '餐厅管理设置',
    pajak_service: '财务与税率',
    tata_letak_meja: '桌位布局',
    pegawai_izin: '员工与权限',
    simpan_pajak: '保存税率设置',
    simpan_tema: '应用主题颜色',
    tambah_meja: '新增桌号',
    hapus_meja: '删除桌号',
    tambah_pegawai: '新增员工',
    ubah_izin: '修改角色权限',
  },
  voucher: {
    judul: '优惠券管理',
    masukkan_kode: '输入优惠码',
    periksa_voucher: '核销检查',
    klaim_diskon: '使用优惠券',
    voucher_valid: '优惠券有效。',
    voucher_tidak_valid: '优惠券无效或已被使用。',
  },
  pelanggan: {
    judul: '美味菜单',
    cari_menu: '搜索美食...',
    semua_kategori: '全部分类',
    makanan: '主食佳肴',
    minuman: '精选饮品',
    camilan: '美味小吃',
    habis: '已售罄',
  },
  keadaan: {
    kosong_judul: '暂无数据',
    kosong_keterangan: '此页面当前没有订单或菜品数据。',
    memuat_judul: '正在加载数据...',
    gagal_judul: '数据加载失败',
    gagal_keterangan: '请检查网络连接后重试。',
    menunggu_terkirim: '等待同步至服务器',
    tanpa_akses: '您没有访问此页面的权限。',
    data_sebagian: '当前显示本地缓存数据。',
    berhasil_disimpan: '保存成功。',
  },
}
