import type { KamusBahasa } from './id'

/**
 * 简体中文翻译字典 (zh)
 */
export const zh: KamusBahasa = {
  umum: {
    aplikasi: 'Sajian',
    selamat_datang: '欢迎光临',
    memuat: '加载中...',
    memproses: '处理中...',
    batal: '取消',
    simpan: '保存',
    tutup: '关闭',
    selesai: '完成',
    coba_lagi: '重试',
    hapus: '删除',
    ubah: '修改',
    konfirmasi: '确认',
    sukses: '成功',
    gagal: '失败',
    kembali: '返回',
    semua: '全部',
    cari: '搜索',
    pilih: '选择',
    keluar: '退出登录',
    bantuan: '使用帮助',
  },
  navigasi: {
    masuk: '员工登录',
    kasir: '收银台',
    dapur: '厨房出餐',
    laporan: '营业与资金报表',
    pengaturan: '系统设置',
    voucher: '优惠券',
    menu_publik: '电子菜单',
    contoh: '组件示例',
    menu_stok: '菜单与库存',
    pegawai: '员工管理',
    riwayat: '交易记录',
    tutup_kas: '交接班与结账',
    pesanan_meja: '桌位订单',
    status_pesanan: '订单状态',
    stok_habis: '标为售罄',
    katalog: '菜单目录',
    voucher_saya: '我的优惠券',
    dasbor_platform: '平台看板',
    resto_penyewa: '入驻餐厅',
    mode_dukungan: '技术支持模式',
  },
  masuk: {
    judul: '员工上班登录',
    pilih_pegawai: '选择员工姓名',
    masukkan_pin: '输入6位PIN码',
    tombol_masuk: '登录',
    ganti_pegawai: '切换员工',
    batal_masuk: '取消登录',
    pin_salah: 'PIN码错误或设备未注册 (AU-101)。',
    sukses_masuk: '登录成功！工作班次已激活。',
  },
  kasir: {
    judul: '收银与点单',
    pilih_meja: '选择桌号',
    keranjang: '点单列表',
    tambah_item: '增加份数',
    kurang_item: '减少份数',
    batal_item: '退点菜品',
    kirim_dapur: '送入厨房',
    beri_diskon: '给予折扣',
    proses_bayar: '结算订单',
    buka_shift: '开班',
    tutup_shift: '交班结账',
    shift_aktif: '当前班次',
    peringatan_belum_buka_kas: '收银员尚未开班。在处理交易前请先开班登记初始备用金。',
    tombol_buka_kas_cepat: '立即开班',
    transaksi_wajib_shift: '只有在收银班次开启后才能处理交易。',
    pengingat_shift_lewat_tengah_malam: '收银班次已过午夜！该班次昨天开启尚未关闭，请立即结班。',
    pengingat_shift_lewat_jam_tutup: '营业时间已结束。当前时间已超过收银结业时间，请进行结班操作。',
    pengingat_shift_durasi_panjang: '收银班次已运行超过12小时。请检查并尽快进行结班。',
    pengingat_shift_mendekati_tutup: '临近餐厅关店时间。请准备清点现金以进行收银结班。',
    tombol_tutup_kas_sekarang: '立即结班',
    tombol_ingatkan_nanti: '稍后提醒',
    tagihan_terbuka: '未结账单',
    total_belanja: '应付总额',
    subtotal: '小计',
    pajak: '餐饮税 (PB1)',
    service: '服务费',
    diskon: '优惠折扣',
    kembalian: '找零',
    uang_diterima: '实收金额',
    metode_tunai: '现金支付',
    metode_qris: 'QRIS扫码',
    metode_kartu: '刷卡支付',
    cari_menu: '搜索菜品或饮料...',
    semua_menu: '全部菜单',
    makanan_utama: '主食佳肴',
    minuman_segar: '冷热饮品',
    cemilan_pendamping: '小吃与配菜',
    favorit: '招牌推荐',
    habis: '已售罄',
    tipe_dinein: '堂食 (Dine In)',
    tipe_takeaway: '外带打包 (Takeaway)',
    tipe_ojol: '外卖配送 (Ojol)',
    pilih_meja_judul: '选择桌号与点餐模式',
    meja_kosong: '空闲',
    meja_terisi: '已占用',
    meja_siap: '就绪',
    tamu: '位顾客',
    catatan_khusus: '快捷口味备注',
    catatan_dapur: '后厨补充说明',
    selesai_lanjutkan: '完成并继续',
    opsi_item: '选择规格',
    harga_dasar: '基础售价',
    varian_ukuran: '规格 / 分量选项',
    tambahan_topping: '加料 / 配料（可选）',
    tambah_ke_pesanan: '加入订单',
    keranjang_kosong: '点单列表为空',
    keranjang_kosong_petunjuk: '点击左侧菜单添加菜品。',
    uang_pas: '刚好付清',
    alasan_selisih_label: '差额原因说明',
    kas_pergerakan: '现金存取记录',
    kas_pergerakan_judul: '现金流动记录',
    kas_pergerakan_petunjuk: '记录非销售交易的现金流入或支出。',
    jenis_kas: '流动类型',
    kas_masuk: '现金转入（补充备用金）',
    kas_keluar: '现金支出（运营花费）',
    kas_setoran: '保险柜/银行存款',
    kas_koreksi: '现金更正',
    nominal_kas: '金额（印尼盾）',
    alasan_kas: '原因 / 用途（必填）',
    alasan_kas_placeholder: '请输入现金流入或支出的原因...',
    disetujui_oleh_label: '批准人（选填）',
    simpan_kas: '保存现金记录',
    sukses_kas_pergerakan: '现金流动记录保存成功。',
    koreksi_modal: '修正开班备用金',
    koreksi_modal_judul: '修正班次备用金',
    koreksi_modal_petunjuk: '开班备用金输入错误可在主管批准下修正，无需删除数据。',
    modal_awal_saat_ini: '当前备用金',
    modal_awal_baru: '新备用金金额 (Rp)',
    selisih_koreksi: '修正差额',
    alasan_koreksi_modal: '修正原因（必填）',
    alasan_koreksi_placeholder: '输入开班备用金修正原因...',
    penyetuju_atasan: '审批主管',
    pilih_atasan: '选择主管',
    pin_atasan: '主管密码 (PIN)',
    pin_atasan_petunjuk: '必须由授权主管亲自输入。',
    simpan_koreksi_modal: '保存备用金修正',
    sukses_koreksi_modal: '开班备用金修正成功。',
  },
  dapur: {
    judul: '厨房与吧台显示',
    antrean_masuk: '待制作订单',
    sedang_dimasak: '制作中',
    siap_saji: '已完成/待上菜',
    mulai_masak: '开始制作',
    selesai_masak: '制作完成',
    tandai_habis: '标为售罄',
    ketersediaan_menu: '菜品状态',
  },
  laporan: {
    judul: '销售与收银报表',
    filter_tanggal: '日期筛选',
    pilih_cabang: '选择分店',
    cetak_laporan: '打印报表',
    ekspor_data: '导出数据',
    omset_penjualan: '总营业额',
    transaksi_selesai: '已结账订单',
    rincian_metode: '支付方式明细',
    kas_harian: '每日现金',
    kas_shift: '班次现金',
    modal_awal: '初始备用金',
    kas_masuk: '现金存入',
    kas_keluar: '现金支出',
    setoran: '银行存款',
    uang_seharusnya: '应有现金',
    uang_fisik: '实际现金',
    selisih: '现金差额',
    alasan_selisih: '差额原因说明',
    omzet_makanan: '食品销售额',
    omzet_minuman: '饮品销售额',
    omzet_lainnya: '其他销售额',
    total_diskon: '折扣与优惠券',
    total_pembatalan: '取消订单数',
    kerugian_pembatalan: '损失金额',
    kasir_buka: '开班收银员',
    kasir_tutup: '结班收银员',
    jam_shift: '班次起止时间',
    status_shift: '班次状态',
    semua_cabang: '所有分店',
    tutup_detail: '收起详情',
    rincian_shift: '班次详情',
    tab_penjualan: '销售',
    tab_kas: '现金与班次',
    omzet_kategori: '各类别营业额',
    tren_harian: '每日销售趋势',
    rentang_tanggal: '日期范围',
    tanggal_mulai: '开始日期',
    tanggal_akhir: '结束日期',
    terapkan_filter: '应用',
    batas_90_hari: '日期范围最长为90天。',
    rata_rata_transaksi: '平均每笔交易',
    total_subtotal: '小计总额',
    total_pajak: '税费总计 (PB1)',
    total_service: '服务费总计',
    jumlah_transaksi: '交易笔数',
    qty_terjual: '已售份数',
    persentase: '占比',
    tanpa_kategori: '未分类',
    tidak_ada_data: '该时间段内无销售数据。',
    muat_ulang: '重新加载',
    tab_menu: '菜品与促销',
    menu_terlaris: '热销菜品',
    urut_nilai: '按销售额排序',
    urut_jumlah: '按份数排序',
    peringkat: '排名',
    diskon_manual: '手动折扣',
    voucher_terpakai: '已使用优惠券',
    biaya_promosi: '促销总成本',
    kasir_pemberi: '收银员',
    disetujui: '审批人',
    potongan: '优惠金额',
    rata_harga: '平均售价',
  },
  pengaturan: {
    judul: '餐厅管理设置',
    pajak_service: '财务与税率',
    tata_letak_meja: '桌位布局',
    pegawai_izin: '员工与权限',
    simpan_pajak: '保存税率设置',
    simpan_tema: '应用主题颜色',
    tambah_meja: '新增桌号',
    hapus_meja: '删除桌号',
    tambah_pegawai: '新增员工',
    ubah_izin: '修改角色权限',
  },
  voucher: {
    judul: '优惠券管理',
    masukkan_kode: '输入优惠码',
    periksa_voucher: '核销检查',
    klaim_diskon: '使用优惠券',
    voucher_valid: '优惠券有效。',
    voucher_tidak_valid: '优惠券无效或已被使用。',
  },
  pelanggan: {
    judul: '美味菜单',
    cari_menu: '搜索美食...',
    semua_kategori: '全部分类',
    makanan: '主食佳肴',
    minuman: '精选饮品',
    camilan: '美味小吃',
    habis: '已售罄',
  },
  keadaan: {
    kosong_judul: '暂无数据',
    kosong_keterangan: '此页面当前没有订单或菜品数据。',
    memuat_judul: '正在加载数据...',
    gagal_judul: '数据加载失败',
    gagal_keterangan: '请检查网络连接后重试。',
    menunggu_terkirim: '等待同步至服务器',
    tanpa_akses: '您没有访问此页面的权限。',
    data_sebagian: '当前显示本地缓存数据。',
    berhasil_disimpan: '保存成功。',
  },
  contoh: {
    judul_halaman: '组件示例 · 第0和1C阶段',
    keterangan_selamat: '收银、后厨、报表与顾客服务融为一体。',
    kartu_tombol: '按钮组件',
    kartu_lencana: '徽章标签',
    kartu_kolom_isian: '表单输入',
    kartu_tabel: '订单表格',
    ragam_5: '5种样式',
    tombol_tahan: '按住',
    tombol_kecil: '紧凑',
    tombol_polos: '扁平',
    tombol_nonaktif: '已禁用',
    tombol_lebar: '通栏宽度',
    lencana_aksen: '主色',
    lencana_lunas: '已结清',
    lencana_belum_bayar: '待支付',
    lencana_dibatalkan: '已取消',
    lencana_dibungkus: '外带打包',
    lencana_netral: '中性',
    nama_pelanggan: '顾客姓名',
    contoh_nama: '例如：张三',
    boleh_kosong: '选填。',
    nomor_meja: '桌号',
    galat_meja: '桌号必填。',
    pemberitahuan_pesan: '通知示例：3号桌订单已保存。',
    tampilkan_pemberitahuan: '重新显示通知',
  },
}
