/**
 * Registri Aksi Aplikasi (T1-32, docs/SPESIFIKASI_UI.md §2)
 * Satu sumber kebenaran untuk seluruh tombol aksi dan interaksi di aplikasi.
 */

import type { PeranPengguna } from './layar'

export type JenisAksi = 'baca' | 'tulis' | 'navigasi'

export interface EntriAksi {
  id: string
  label: string
  layar: string
  peran: PeranPengguna[]
  izin: string | null
  rpc: string | null
  jenis: JenisAksi
  konfirmasi: string | null
  pin: boolean
  audit: boolean
  sukses: string | null
  gagal: string | null
  uji: string[]
  sembunyikanBilaTanpaIzin: boolean
  alasanNonaktifBilaTanpaIzin?: string
}

export const REGISTRI_AKSI: Record<string, EntriAksi> = {
  // ------------------------------------------------------------- Layar Masuk
  'masuk.verifikasi_pin': {
    id: 'masuk.verifikasi_pin',
    label: 'Masuk',
    layar: 'masuk',
    peran: ['pemilik_platform', 'owner_pusat', 'admin_cabang', 'kasir', 'pelayan', 'dapur'],
    izin: null,
    rpc: 'verifikasi_pin',
    jenis: 'tulis',
    konfirmasi: null,
    pin: false,
    audit: false,
    sukses: 'Selamat bertugas! Sesi masuk aktif.',
    gagal: 'PIN salah atau perangkat belum terdaftar (AU-101).',
    uji: ['uji_masuk_pin_sah', 'uji_masuk_pin_salah'],
    sembunyikanBilaTanpaIzin: false,
  },
  'masuk.ganti_pengguna': {
    id: 'masuk.ganti_pengguna',
    label: 'Ganti Pegawai',
    layar: 'masuk',
    peran: ['pemilik_platform', 'owner_pusat', 'admin_cabang', 'kasir', 'pelayan', 'dapur'],
    izin: null,
    rpc: null,
    jenis: 'navigasi',
    konfirmasi: null,
    pin: false,
    audit: false,
    sukses: null,
    gagal: null,
    uji: ['uji_navigasi_ganti_pegawai'],
    sembunyikanBilaTanpaIzin: false,
  },
  'masuk.batal': {
    id: 'masuk.batal',
    label: 'Batal',
    layar: 'masuk',
    peran: ['pemilik_platform', 'owner_pusat', 'admin_cabang', 'kasir', 'pelayan', 'dapur'],
    izin: null,
    rpc: null,
    jenis: 'navigasi',
    konfirmasi: null,
    pin: false,
    audit: false,
    sukses: null,
    gagal: null,
    uji: ['uji_batal_masuk'],
    sembunyikanBilaTanpaIzin: false,
  },

  // ------------------------------------------------------------- Layar Kasir
  'kasir.tambah_item': {
    id: 'kasir.tambah_item',
    label: 'Tambah Item',
    layar: 'kasir',
    peran: ['owner_pusat', 'admin_cabang', 'kasir'],
    izin: null,
    rpc: 'hitung_total',
    jenis: 'tulis',
    konfirmasi: null,
    pin: false,
    audit: false,
    sukses: 'Item ditambahkan ke pesanan.',
    gagal: 'Gagal menambahkan item ke keranjang.',
    uji: ['uji_kasir_tambah_item'],
    sembunyikanBilaTanpaIzin: true,
  },
  'kasir.kurang_item': {
    id: 'kasir.kurang_item',
    label: 'Kurangi Item',
    layar: 'kasir',
    peran: ['owner_pusat', 'admin_cabang', 'kasir'],
    izin: null,
    rpc: 'hitung_total',
    jenis: 'tulis',
    konfirmasi: null,
    pin: false,
    audit: false,
    sukses: 'Jumlah item dikurangi.',
    gagal: 'Gagal mengubah jumlah item.',
    uji: ['uji_kasir_kurang_item'],
    sembunyikanBilaTanpaIzin: true,
  },
  'kasir.batal_item': {
    id: 'kasir.batal_item',
    label: 'Batalkan Item',
    layar: 'kasir',
    peran: ['owner_pusat', 'admin_cabang', 'kasir'],
    izin: 'void_sebelum_dapur',
    rpc: 'hitung_total',
    jenis: 'tulis',
    konfirmasi: 'Batalkan item pesanan ini?',
    pin: false,
    audit: true,
    sukses: 'Item pesanan berhasil dibatalkan.',
    gagal: 'Pembatalan gagal. Memerlukan izin atau persetujuan supervisor.',
    uji: ['uji_kasir_batal_item_pra_dapur'],
    sembunyikanBilaTanpaIzin: false,
    alasanNonaktifBilaTanpaIzin: 'Memerlukan izin void pembatalan.',
  },
  'kasir.kirim_dapur': {
    id: 'kasir.kirim_dapur',
    label: 'Kirim ke Dapur',
    layar: 'kasir',
    peran: ['owner_pusat', 'admin_cabang', 'kasir'],
    izin: null,
    rpc: 'hitung_total',
    jenis: 'tulis',
    konfirmasi: null,
    pin: false,
    audit: false,
    sukses: 'Tiket pesanan dikirim ke dapur.',
    gagal: 'Gagal mengirim pesanan ke dapur.',
    uji: ['uji_kirim_tiket_dapur'],
    sembunyikanBilaTanpaIzin: true,
  },
  'kasir.beri_diskon': {
    id: 'kasir.beri_diskon',
    label: 'Beri Diskon',
    layar: 'kasir',
    peran: ['owner_pusat', 'admin_cabang', 'kasir'],
    izin: 'beri_diskon',
    // T5-05: diskon TIDAK lewat RPC — ia dicatat sebagai baris `diskon_transaksi`
    // (insert biasa yang dijaga RLS), dan pagar batas/PIN atasan ditegakkan pemicu
    // `picu_diskon_batas` (migrasi 0041). Kolom ini sengaja `null`: menuliskan nama
    // tabel di sini membuat pemeriksa peta-ui mencarinya sebagai fungsi dan gagal,
    // sekaligus menyesatkan pembaca seolah ada RPC bernama sama.
    rpc: null,
    jenis: 'tulis',
    konfirmasi: 'Terapkan diskon pada transaksi ini?',
    // Bukan selalu: PIN atasan diminta hanya bila nilainya di atas batas pemakai.
    // Layar menanyakannya sendiri (DiskonManual.tsx) dan peladen menegakkannya.
    pin: false,
    audit: true,
    sukses: 'Diskon berhasil diterapkan pada pesanan.',
    gagal: 'Gagal menerapkan diskon atau melebihi batas hak akses.',
    uji: ['uji_kasir_diskon_transaksi'],
    sembunyikanBilaTanpaIzin: false,
    alasanNonaktifBilaTanpaIzin: 'Memerlukan izin pemberian diskon.',
  },
  'kasir.proses_bayar': {
    id: 'kasir.proses_bayar',
    label: 'Bayar Pesanan',
    layar: 'kasir',
    peran: ['owner_pusat', 'admin_cabang', 'kasir'],
    izin: null,
    // Sejak T5-02 uang masuk HANYA lewat RPC bayar_pesanan (migrasi 0039):
    // hitung_total hanya penulis kolom uang pesanan, bukan pencatat pembayaran.
    rpc: 'bayar_pesanan',
    jenis: 'tulis',
    konfirmasi: 'Periksa nominal dan metode, lalu catat pembayaran?',
    pin: false,
    audit: true,
    sukses: 'Pembayaran tercatat. Kembalian dan status lunas mengikuti hitungan peladen.',
    gagal: 'Pembayaran gagal diproses.',
    uji: [
      'uji_kasir_bayar_tunai_lunas',
      'src/hook/useBayar.test.tsx',
      'src/layar/kasir/Bayar.test.tsx',
    ],
    sembunyikanBilaTanpaIzin: true,
  },
  'kasir.buka_shift': {
    id: 'kasir.buka_shift',
    label: 'Buka Shift',
    layar: 'kasir',
    peran: ['owner_pusat', 'admin_cabang', 'kasir'],
    izin: null,
    rpc: 'buka_shift',
    jenis: 'tulis',
    konfirmasi: null,
    pin: false,
    audit: true,
    sukses: 'Shift kasir dibuka.',
    gagal: 'Gagal membuka shift kasir.',
    uji: ['uji_kasir_buka_shift', 'src/layar/kasir/BukaKas.test.tsx'],
    sembunyikanBilaTanpaIzin: true,
  },
  'kasir.tutup_shift': {
    id: 'kasir.tutup_shift',
    label: 'Tutup Shift',
    layar: 'kasir',
    peran: ['owner_pusat', 'admin_cabang', 'kasir'],
    izin: 'tutup_kas',
    rpc: 'tutup_shift',
    jenis: 'tulis',
    konfirmasi: 'Tutup shift kasir dan cetak ringkasan kas?',
    pin: false,
    audit: true,
    sukses: 'Shift kasir berhasil ditutup.',
    gagal: 'Gagal menutup shift kasir.',
    uji: ['uji_kasir_tutup_shift', 'src/layar/kasir/TutupKas.test.tsx'],
    sembunyikanBilaTanpaIzin: false,
    alasanNonaktifBilaTanpaIzin: 'Memerlukan izin penutupan kas.',
  },
  'kasir.kas_pergerakan': {
    id: 'kasir.kas_pergerakan',
    label: 'Catat Kas Masuk/Keluar',
    layar: 'kasir',
    peran: ['owner_pusat', 'admin_cabang', 'kasir'],
    izin: 'tutup_kas',
    rpc: 'kas_pergerakan',
    jenis: 'tulis',
    konfirmasi: 'Simpan pergerakan kas ini?',
    pin: false,
    audit: true,
    sukses: 'Pergerakan kas berhasil dicatat.',
    gagal: 'Gagal mencatat pergerakan kas.',
    uji: ['uji_kasir_kas_pergerakan', 'src/layar/kasir/KasKeluarMasuk.test.tsx'],
    sembunyikanBilaTanpaIzin: false,
    alasanNonaktifBilaTanpaIzin: 'Memerlukan wewenang pengelolaan kas.',
  },

  // ------------------------------------------------------------- Layar Dapur
  'dapur.mulai_masak': {
    id: 'dapur.mulai_masak',
    label: 'Mulai Masak',
    layar: 'dapur',
    peran: ['owner_pusat', 'admin_cabang', 'kasir', 'dapur'],
    izin: null,
    rpc: null,
    jenis: 'tulis',
    konfirmasi: null,
    pin: false,
    audit: false,
    sukses: 'Status pesanan diubah menjadi sedang dimasak.',
    gagal: 'Gagal mengubah status pengerjaan pesanan.',
    uji: ['uji_dapur_mulai_masak'],
    sembunyikanBilaTanpaIzin: true,
  },
  'dapur.selesai_masak': {
    id: 'dapur.selesai_masak',
    label: 'Siap Saji',
    layar: 'dapur',
    peran: ['owner_pusat', 'admin_cabang', 'kasir', 'dapur'],
    izin: null,
    rpc: null,
    jenis: 'tulis',
    konfirmasi: null,
    pin: false,
    audit: false,
    sukses: 'Pesanan siap diantar ke meja.',
    gagal: 'Gagal memperbarui status saji pesanan.',
    uji: ['uji_dapur_selesai_masak'],
    sembunyikanBilaTanpaIzin: true,
  },
  'dapur.tandai_habis': {
    id: 'dapur.tandai_habis',
    label: 'Tandai Habis',
    layar: 'dapur',
    peran: ['owner_pusat', 'admin_cabang', 'dapur'],
    izin: 'ubah_stok',
    rpc: null,
    jenis: 'tulis',
    konfirmasi: 'Tandai menu ini habis di kasir dan katalog?',
    pin: false,
    audit: true,
    sukses: 'Menu ditandai habis.',
    gagal: 'Gagal memperbarui ketersediaan menu.',
    uji: ['uji_dapur_tandai_menu_habis'],
    sembunyikanBilaTanpaIzin: false,
    alasanNonaktifBilaTanpaIzin: 'Memerlukan izin ubah stok/ketersediaan.',
  },

  // ----------------------------------------------------------- Layar Laporan
  'laporan.filter_tanggal': {
    id: 'laporan.filter_tanggal',
    label: 'Filter Tanggal',
    layar: 'laporan',
    peran: ['owner_pusat', 'admin_cabang'],
    izin: 'lihat_laporan',
    rpc: null,
    jenis: 'baca',
    konfirmasi: null,
    pin: false,
    audit: false,
    sukses: null,
    gagal: 'Gagal memuat rentang tanggal laporan.',
    uji: ['uji_laporan_filter_tanggal'],
    sembunyikanBilaTanpaIzin: true,
  },
  'laporan.pilih_cabang': {
    id: 'laporan.pilih_cabang',
    label: 'Pilih Cabang',
    layar: 'laporan',
    peran: ['owner_pusat', 'admin_cabang'],
    izin: 'lihat_laporan',
    rpc: null,
    jenis: 'baca',
    konfirmasi: null,
    pin: false,
    audit: false,
    sukses: null,
    gagal: 'Gagal mengganti cabang laporan.',
    uji: ['uji_laporan_pilih_cabang'],
    sembunyikanBilaTanpaIzin: true,
  },
  'laporan.cetak_laporan': {
    id: 'laporan.cetak_laporan',
    label: 'Cetak Laporan',
    layar: 'laporan',
    peran: ['owner_pusat', 'admin_cabang'],
    izin: 'lihat_laporan',
    rpc: null,
    jenis: 'baca',
    konfirmasi: null,
    pin: false,
    audit: false,
    sukses: 'Perintah cetak dikirim ke printer.',
    gagal: 'Gagal mencetak laporan keuangan.',
    uji: ['uji_laporan_cetak'],
    sembunyikanBilaTanpaIzin: true,
  },
  'laporan.ekspor_data': {
    id: 'laporan.ekspor_data',
    label: 'Ekspor Ringkasan',
    layar: 'laporan',
    peran: ['owner_pusat', 'admin_cabang'],
    izin: 'lihat_laporan',
    rpc: null,
    jenis: 'baca',
    konfirmasi: null,
    pin: false,
    audit: false,
    sukses: 'Laporan berhasil diekspor.',
    gagal: 'Gagal mengekspor data laporan.',
    uji: ['uji_laporan_ekspor'],
    sembunyikanBilaTanpaIzin: true,
  },

  // -------------------------------------------------------- Layar Pengaturan
  'pengaturan.simpan_pajak': {
    id: 'pengaturan.simpan_pajak',
    label: 'Simpan Pajak & Service',
    layar: 'pengaturan',
    peran: ['owner_pusat'],
    izin: 'atur_pengaturan',
    rpc: 'simpan_operasional',
    jenis: 'tulis',
    konfirmasi: 'Simpan perubahan tarif pajak dan service?',
    pin: false,
    audit: true,
    sukses: 'Pengaturan operasional resto berhasil disimpan.',
    gagal: 'Gagal menyimpan pengaturan operasional.',
    uji: ['uji_pengaturan_pajak', 'uji_pengaturan_operasional'],
    sembunyikanBilaTanpaIzin: true,
  },
  'pengaturan.simpan_tema': {
    id: 'pengaturan.simpan_tema',
    label: 'Terapkan Tema',
    layar: 'pengaturan',
    peran: ['owner_pusat', 'admin_cabang'],
    izin: 'atur_pengaturan',
    rpc: 'simpan_tema',
    jenis: 'tulis',
    konfirmasi: null,
    pin: false,
    audit: true,
    sukses: 'Tema warna resto berhasil diperbarui.',
    gagal: 'Gagal menyimpan pilihan tema.',
    uji: ['uji_pengaturan_tema'],
    sembunyikanBilaTanpaIzin: true,
  },
  'pengaturan.tambah_meja': {
    id: 'pengaturan.tambah_meja',
    label: 'Tambah Meja',
    layar: 'pengaturan',
    peran: ['owner_pusat', 'admin_cabang'],
    izin: 'atur_pengaturan',
    rpc: 'simpan_meja',
    jenis: 'tulis',
    konfirmasi: null,
    pin: false,
    audit: true,
    sukses: 'Nomor meja baru berhasil didaftarkan.',
    gagal: 'Gagal menambahkan meja.',
    uji: ['uji_pengaturan_tambah_meja'],
    sembunyikanBilaTanpaIzin: true,
  },
  'pengaturan.hapus_meja': {
    id: 'pengaturan.hapus_meja',
    label: 'Hapus Meja',
    layar: 'pengaturan',
    peran: ['owner_pusat', 'admin_cabang'],
    izin: 'atur_pengaturan',
    rpc: 'hapus_meja',
    jenis: 'tulis',
    konfirmasi: 'Hapus meja ini dari cabang?',
    pin: false,
    audit: true,
    sukses: 'Meja berhasil dihapus.',
    gagal: 'Meja tidak dapat dihapus jika memiliki riwayat aktif.',
    uji: ['uji_pengaturan_hapus_meja'],
    sembunyikanBilaTanpaIzin: true,
  },
  'pengaturan.simpan_kategori': {
    id: 'pengaturan.simpan_kategori',
    label: 'Simpan Kategori Menu',
    layar: 'pengaturan',
    peran: ['owner_pusat', 'admin_cabang'],
    izin: 'atur_pengaturan',
    rpc: 'simpan_kategori_menu',
    jenis: 'tulis',
    konfirmasi: null,
    pin: false,
    audit: true,
    sukses: 'Kategori menu berhasil disimpan.',
    gagal: 'Gagal menyimpan kategori menu.',
    uji: ['uji_pengaturan_simpan_kategori'],
    sembunyikanBilaTanpaIzin: true,
  },
  'pengaturan.hapus_kategori': {
    id: 'pengaturan.hapus_kategori',
    label: 'Hapus Kategori Menu',
    layar: 'pengaturan',
    peran: ['owner_pusat', 'admin_cabang'],
    izin: 'atur_pengaturan',
    rpc: 'hapus_kategori_menu',
    jenis: 'tulis',
    konfirmasi: 'Hapus kategori ini? Kategori tidak boleh memiliki menu.',
    pin: false,
    audit: true,
    sukses: 'Kategori menu berhasil dihapus.',
    gagal: 'Gagal menghapus kategori menu.',
    uji: ['uji_pengaturan_hapus_kategori'],
    sembunyikanBilaTanpaIzin: true,
  },
  'pengaturan.simpan_menu': {
    id: 'pengaturan.simpan_menu',
    label: 'Simpan Menu',
    layar: 'pengaturan',
    peran: ['owner_pusat', 'admin_cabang'],
    izin: 'atur_pengaturan',
    rpc: 'simpan_menu',
    jenis: 'tulis',
    konfirmasi: null,
    pin: false,
    audit: true,
    sukses: 'Menu berhasil disimpan.',
    gagal: 'Gagal menyimpan menu.',
    uji: ['uji_pengaturan_simpan_menu'],
    sembunyikanBilaTanpaIzin: true,
  },
  'pengaturan.hapus_menu': {
    id: 'pengaturan.hapus_menu',
    label: 'Hapus Menu',
    layar: 'pengaturan',
    peran: ['owner_pusat', 'admin_cabang'],
    izin: 'atur_pengaturan',
    rpc: 'hapus_menu',
    jenis: 'tulis',
    konfirmasi: 'Hapus menu ini? Menu yang pernah dipesan hanya boleh dinonaktifkan.',
    pin: false,
    audit: true,
    sukses: 'Menu berhasil dihapus.',
    gagal: 'Menu tidak dapat dihapus jika memiliki riwayat pesanan.',
    uji: ['uji_pengaturan_hapus_menu'],
    sembunyikanBilaTanpaIzin: true,
  },
  'pengaturan.simpan_menu_cabang': {
    id: 'pengaturan.simpan_menu_cabang',
    label: 'Simpan Menu Cabang',
    layar: 'pengaturan',
    peran: ['owner_pusat', 'admin_cabang'],
    izin: 'atur_pengaturan',
    rpc: 'simpan_menu_cabang',
    jenis: 'tulis',
    konfirmasi: null,
    pin: false,
    audit: true,
    sukses: 'Pengaturan harga & ketersediaan menu cabang berhasil disimpan.',
    gagal: 'Gagal menyimpan pengaturan menu cabang.',
    uji: ['uji_pengaturan_simpan_menu_cabang'],
    sembunyikanBilaTanpaIzin: true,
  },
  'pengaturan.salin_harga_cabang': {
    id: 'pengaturan.salin_harga_cabang',
    label: 'Salin Menu Cabang',
    layar: 'pengaturan',
    peran: ['owner_pusat'],
    izin: 'atur_pengaturan',
    rpc: 'salin_harga_cabang',
    jenis: 'tulis',
    konfirmasi:
      'Salin seluruh konfigurasi harga dan ketersediaan menu dari cabang asal ke cabang tujuan?',
    pin: false,
    audit: true,
    sukses: 'Konfigurasi menu cabang berhasil disalin.',
    gagal: 'Gagal menyalin konfigurasi menu cabang.',
    uji: ['uji_pengaturan_salin_harga_cabang'],
    sembunyikanBilaTanpaIzin: true,
  },
  'pengaturan.simpan_metode_bayar': {
    id: 'pengaturan.simpan_metode_bayar',
    label: 'Simpan Metode Pembayaran',
    layar: 'pengaturan',
    peran: ['owner_pusat', 'admin_cabang'],
    izin: 'atur_pengaturan',
    rpc: 'simpan_metode_bayar',
    jenis: 'tulis',
    konfirmasi: null,
    pin: false,
    audit: true,
    sukses: 'Metode pembayaran berhasil disimpan.',
    gagal: 'Gagal menyimpan metode pembayaran.',
    uji: ['uji_pengaturan_simpan_metode_bayar'],
    sembunyikanBilaTanpaIzin: true,
  },
  'pengaturan.hapus_metode_bayar': {
    id: 'pengaturan.hapus_metode_bayar',
    label: 'Hapus Metode Pembayaran',
    layar: 'pengaturan',
    peran: ['owner_pusat'],
    izin: 'atur_pengaturan',
    rpc: 'hapus_metode_bayar',
    jenis: 'tulis',
    konfirmasi:
      'Hapus metode pembayaran ini? Metode yang pernah digunakan hanya boleh dinonaktifkan.',
    pin: false,
    audit: true,
    sukses: 'Metode pembayaran berhasil dihapus.',
    gagal: 'Metode pembayaran tidak dapat dihapus jika memiliki riwayat transaksi.',
    uji: ['uji_pengaturan_hapus_metode_bayar'],
    sembunyikanBilaTanpaIzin: true,
  },
  'pengaturan.simpan_aturan_tip': {
    id: 'pengaturan.simpan_aturan_tip',
    label: 'Simpan Aturan Tip',
    layar: 'pengaturan',
    peran: ['owner_pusat'],
    izin: 'atur_pengaturan',
    rpc: 'simpan_aturan_tip',
    jenis: 'tulis',
    konfirmasi: null,
    pin: false,
    audit: true,
    sukses: 'Aturan tip berhasil disimpan.',
    gagal: 'Gagal menyimpan aturan tip.',
    uji: ['uji_pengaturan_simpan_aturan_tip'],
    sembunyikanBilaTanpaIzin: true,
  },
  'pengaturan.tambah_pegawai': {
    id: 'pengaturan.tambah_pegawai',
    label: 'Tambah Pegawai',
    layar: 'pengaturan',
    peran: ['owner_pusat', 'admin_cabang'],
    izin: 'kelola_pegawai',
    rpc: 'simpan_pegawai',
    jenis: 'tulis',
    konfirmasi: null,
    pin: false,
    audit: true,
    sukses: 'Pegawai baru berhasil ditambahkan.',
    gagal: 'Gagal mendaftarkan akun pegawai baru.',
    uji: ['uji_pengaturan_tambah_pegawai'],
    sembunyikanBilaTanpaIzin: true,
  },
  'pengaturan.ubah_izin': {
    id: 'pengaturan.ubah_izin',
    label: 'Ubah Izin Peran',
    layar: 'pengaturan',
    peran: ['owner_pusat'],
    izin: 'kelola_pegawai',
    rpc: 'set_izin',
    jenis: 'tulis',
    konfirmasi: 'Simpan konfigurasi izin peran ini?',
    pin: false,
    audit: true,
    sukses: 'Izin peran berhasil diperbarui.',
    gagal: 'Gagal memperbarui izin pegawai.',
    uji: ['uji_pengaturan_ubah_izin'],
    sembunyikanBilaTanpaIzin: true,
  },
  'pengaturan.ubah_status_pegawai': {
    id: 'pengaturan.ubah_status_pegawai',
    label: 'Ubah Status Pegawai',
    layar: 'pengaturan',
    peran: ['owner_pusat', 'admin_cabang'],
    izin: 'kelola_pegawai',
    rpc: 'set_status_pengguna',
    jenis: 'tulis',
    konfirmasi: null,
    pin: false,
    audit: true,
    sukses: 'Status keaktifan pegawai berhasil diperbarui.',
    gagal: 'Gagal memperbarui status pegawai.',
    uji: ['uji_pengaturan_ubah_status_pegawai'],
    sembunyikanBilaTanpaIzin: true,
  },
  'pengaturan.reset_pin_pegawai': {
    id: 'pengaturan.reset_pin_pegawai',
    label: 'Reset PIN Pegawai',
    layar: 'pengaturan',
    peran: ['owner_pusat', 'admin_cabang'],
    izin: 'kelola_pegawai',
    rpc: 'reset_pin_pegawai',
    jenis: 'tulis',
    konfirmasi: 'Atur ulang PIN akun pegawai ini?',
    pin: false,
    audit: true,
    sukses: 'PIN pegawai berhasil diatur ulang.',
    gagal: 'Gagal mengatur ulang PIN pegawai.',
    uji: ['uji_pengaturan_reset_pin_pegawai'],
    sembunyikanBilaTanpaIzin: true,
  },

  // ----------------------------------------------------------- Layar Voucher
  'voucher.cek_kode': {
    id: 'voucher.cek_kode',
    label: 'Periksa Voucher',
    layar: 'voucher',
    peran: ['owner_pusat', 'admin_cabang', 'kasir'],
    izin: null,
    rpc: null,
    jenis: 'baca',
    konfirmasi: null,
    pin: false,
    audit: false,
    sukses: 'Voucher valid.',
    gagal: 'Voucher tidak ditemukan atau tidak aktif.',
    uji: ['uji_voucher_cek_kode'],
    sembunyikanBilaTanpaIzin: true,
  },
  'voucher.klaim_diskon': {
    id: 'voucher.klaim_diskon',
    label: 'Terapkan Voucher',
    layar: 'voucher',
    peran: ['owner_pusat', 'admin_cabang', 'kasir'],
    izin: 'pakai_voucher',
    rpc: 'hitung_total',
    jenis: 'tulis',
    konfirmasi: 'Gunakan voucher pada tagihan transaksi ini?',
    pin: false,
    audit: true,
    sukses: 'Voucher berhasil digunakan.',
    gagal: 'Klaim voucher gagal.',
    uji: ['uji_voucher_klaim_diskon'],
    sembunyikanBilaTanpaIzin: false,
    alasanNonaktifBilaTanpaIzin: 'Memerlukan izin penggunaan voucher.',
  },
  'voucher.batal': {
    id: 'voucher.batal',
    label: 'Tutup',
    layar: 'voucher',
    peran: ['owner_pusat', 'admin_cabang', 'kasir'],
    izin: null,
    rpc: null,
    jenis: 'navigasi',
    konfirmasi: null,
    pin: false,
    audit: false,
    sukses: null,
    gagal: null,
    uji: ['uji_voucher_batal'],
    sembunyikanBilaTanpaIzin: false,
  },

  // -------------------------------------------------- Layar Pelanggan Publik
  'pelanggan.cari_menu': {
    id: 'pelanggan.cari_menu',
    label: 'Cari Menu',
    layar: 'pelanggan-publik',
    peran: ['pelanggan', 'kasir', 'pelayan', 'admin_cabang', 'owner_pusat', 'pemilik_platform'],
    izin: null,
    rpc: null,
    jenis: 'baca',
    konfirmasi: null,
    pin: false,
    audit: false,
    sukses: null,
    gagal: null,
    uji: ['uji_pelanggan_cari_menu'],
    sembunyikanBilaTanpaIzin: false,
  },
  'pelanggan.filter_kategori': {
    id: 'pelanggan.filter_kategori',
    label: 'Pilih Kategori',
    layar: 'pelanggan-publik',
    peran: ['pelanggan', 'kasir', 'pelayan', 'admin_cabang', 'owner_pusat', 'pemilik_platform'],
    izin: null,
    rpc: null,
    jenis: 'baca',
    konfirmasi: null,
    pin: false,
    audit: false,
    sukses: null,
    gagal: null,
    uji: ['uji_pelanggan_filter_kategori'],
    sembunyikanBilaTanpaIzin: false,
  },

  // ------------------------------------------------------------ Layar Contoh
  'contoh.ganti_tema': {
    id: 'contoh.ganti_tema',
    label: 'Ganti Tema',
    layar: 'contoh',
    peran: [
      'owner_pusat',
      'admin_cabang',
      'kasir',
      'pelayan',
      'dapur',
      'pemilik_platform',
      'pelanggan',
    ],
    izin: null,
    rpc: null,
    jenis: 'navigasi',
    konfirmasi: null,
    pin: false,
    audit: false,
    sukses: 'Tema berhasil diubah.',
    gagal: null,
    uji: ['uji_contoh_ganti_tema'],
    sembunyikanBilaTanpaIzin: false,
  },
  'contoh.ganti_kerapatan': {
    id: 'contoh.ganti_kerapatan',
    label: 'Ganti Kerapatan',
    layar: 'contoh',
    peran: [
      'owner_pusat',
      'admin_cabang',
      'kasir',
      'pelayan',
      'dapur',
      'pemilik_platform',
      'pelanggan',
    ],
    izin: null,
    rpc: null,
    jenis: 'navigasi',
    konfirmasi: null,
    pin: false,
    audit: false,
    sukses: 'Kerapatan berhasil diubah.',
    gagal: null,
    uji: ['uji_contoh_ganti_kerapatan'],
    sembunyikanBilaTanpaIzin: false,
  },
  'contoh.picu_toast': {
    id: 'contoh.picu_toast',
    label: 'Picu Toast Pemberitahuan',
    layar: 'contoh',
    peran: [
      'owner_pusat',
      'admin_cabang',
      'kasir',
      'pelayan',
      'dapur',
      'pemilik_platform',
      'pelanggan',
    ],
    izin: null,
    rpc: null,
    jenis: 'navigasi',
    konfirmasi: null,
    pin: false,
    audit: false,
    sukses: 'Toast berhasil ditampilkan.',
    gagal: null,
    uji: ['uji_contoh_picu_toast'],
    sembunyikanBilaTanpaIzin: false,
  },

  // ------------------------------------------------------------- Layar Bar (T4-02)
  'bar.mulai_buat': {
    id: 'bar.mulai_buat',
    label: 'Mulai Buat',
    layar: 'bar',
    peran: ['owner_pusat', 'admin_cabang', 'kasir', 'dapur'],
    izin: null,
    rpc: 'set_status_item',
    jenis: 'tulis',
    konfirmasi: null,
    pin: false,
    audit: false,
    sukses: 'Minuman sedang dibuat.',
    gagal: 'Gagal mengubah status minuman.',
    uji: ['uji_status_item_transisi'],
    sembunyikanBilaTanpaIzin: true,
  },
  'bar.selesai_buat': {
    id: 'bar.selesai_buat',
    label: 'Siap Saji',
    layar: 'bar',
    peran: ['owner_pusat', 'admin_cabang', 'kasir', 'dapur'],
    izin: null,
    rpc: 'set_status_item',
    jenis: 'tulis',
    konfirmasi: null,
    pin: false,
    audit: false,
    sukses: 'Minuman siap diantar.',
    gagal: 'Gagal memperbarui status minuman.',
    uji: ['uji_status_item_transisi'],
    sembunyikanBilaTanpaIzin: true,
  },

  // ----------------------------------------------------------- Layar Stok (T4-06)
  'stok.catat_perubahan': {
    id: 'stok.catat_perubahan',
    label: 'Catat Perubahan Stok',
    layar: 'stok',
    peran: ['owner_pusat', 'admin_cabang', 'dapur'],
    izin: 'ubah_stok',
    rpc: 'set_stok',
    jenis: 'tulis',
    konfirmasi: 'Catat perubahan stok bahan ini ke buku besar?',
    pin: false,
    audit: true,
    sukses: 'Perubahan stok tercatat di buku besar.',
    gagal: 'Gagal mencatat perubahan stok.',
    uji: ['uji_set_stok'],
    sembunyikanBilaTanpaIzin: false,
    alasanNonaktifBilaTanpaIzin: 'Memerlukan izin ubah stok.',
  },
  'stok.ke_opname': {
    id: 'stok.ke_opname',
    label: 'Ke Opname',
    layar: 'stok',
    peran: ['owner_pusat', 'admin_cabang', 'dapur'],
    izin: null,
    rpc: null,
    jenis: 'navigasi',
    konfirmasi: null,
    pin: false,
    audit: false,
    sukses: null,
    gagal: null,
    uji: ['uji_opname_stok'],
    sembunyikanBilaTanpaIzin: false,
  },

  // ---------------------------------------------------------- Layar Opname (T4-07)
  'opname.catat_fisik': {
    id: 'opname.catat_fisik',
    label: 'Catat Jumlah Fisik',
    layar: 'opname',
    peran: ['owner_pusat', 'admin_cabang', 'dapur'],
    izin: 'ubah_stok',
    rpc: 'opname_stok',
    jenis: 'tulis',
    konfirmasi: 'Catat hasil hitung fisik dan selisihnya ke buku besar?',
    pin: false,
    audit: true,
    sukses: 'Hasil opname tercatat; selisih tampil apa adanya.',
    gagal: 'Gagal mencatat hasil opname.',
    uji: ['uji_opname_stok'],
    sembunyikanBilaTanpaIzin: false,
    alasanNonaktifBilaTanpaIzin: 'Memerlukan izin ubah stok.',
  },
  'opname.kembali_stok': {
    id: 'opname.kembali_stok',
    label: 'Kembali ke Stok',
    layar: 'opname',
    peran: ['owner_pusat', 'admin_cabang', 'dapur'],
    izin: null,
    rpc: null,
    jenis: 'navigasi',
    konfirmasi: null,
    pin: false,
    audit: false,
    sukses: null,
    gagal: null,
    uji: ['uji_opname_stok'],
    sembunyikanBilaTanpaIzin: false,
  },
}
