#!/usr/bin/env node
//
// sync-version.mjs — make package.json the single source of the version.
//
//   node scripts/sync-version.mjs          write the derived files
//   node scripts/sync-version.mjs --check   verify they are current (exit 1 if not)
//
// WHY THIS EXISTS
//
// ios-agent-mcp@2.0.1 shipped to npm with an mcp.json declaring "1.0.0". The
// version lived in four hand-maintained places, so one of them was always
// wrong, and nothing checked. A published manifest that lies about its own
// version is the kind of defect nobody notices until someone is debugging a
// client and cannot work out which build they have.
//
// Generating instead of checking makes the drift impossible rather than
// merely detectable. `--check` exists for CI, so a hand-edit still fails.

import { readFile, writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const CHECK = process.argv.includes("--check");

const pkg = JSON.parse(await readFile(join(ROOT, "package.json"), "utf8"));
const VERSION = pkg.version;

if (!/^\d+\.\d+\.\d+(?:-[0-9A-Za-z.-]+)?$/.test(VERSION)) {
  console.error(`package.json version is not semver: ${VERSION}`);
  process.exit(1);
}

/** Generated TypeScript, so the CLI and the MCP handshake cannot disagree. */
const versionModule = `// GENERATED by scripts/sync-version.mjs — do not edit.
// The version lives in package.json. Run \`npm run sync-version\` after changing it.
export const VERSION = "${VERSION}";
`;

const targets = [];

targets.push({
  path: "src/version.ts",
  next: versionModule,
});

const manifest = JSON.parse(await readFile(join(ROOT, "mcp.json"), "utf8"));
if (manifest.version !== VERSION) {
  manifest.version = VERSION;
}
targets.push({
  path: "mcp.json",
  next: `${JSON.stringify(manifest, null, 2)}\n`,
});

const lock = JSON.parse(await readFile(join(ROOT, "package-lock.json"), "utf8"));
lock.version = VERSION;
if (lock.packages?.[""]) {
  lock.packages[""].version = VERSION;
}
targets.push({
  path: "package-lock.json",
  next: `${JSON.stringify(lock, null, 2)}\n`,
});

let stale = 0;

for (const target of targets) {
  const full = join(ROOT, target.path);
  let current = null;
  try {
    current = await readFile(full, "utf8");
  } catch {
    // missing counts as stale
  }

  if (current === target.next) continue;

  if (CHECK) {
    console.log(`STALE    ${target.path}`);
    stale += 1;
  } else {
    await writeFile(full, target.next, "utf8");
    console.log(`wrote    ${target.path}`);
  }
}

if (CHECK) {
  if (stale > 0) {
    console.error(
      `\n${stale} file(s) disagree with package.json (${VERSION}).\n` +
        "Fix: npm run sync-version && git add -A",
    );
    process.exit(1);
  }
  console.log(`OK — every version reference matches package.json (${VERSION})`);
} else {
  console.log(`Synced ${targets.length} files to ${VERSION}`);
}
